<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\ContactsController;
use FortisAPILib\Exceptions;

class ContactsControllerTest extends BaseTestController
{
    /**
     * @var ContactsController ContactsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getContactsController();
    }

    public function testContactsSearch()
    {
        // Parameters for the API call
        $locationId = '11e95f8ec39de8fbdb0a4f1a';
        $page = null;
        $keyword = null;
        $active = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->contactsSearch($locationId, $page, $keyword, $active);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"ContactSearchsCollection","list":[{"location_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","account_number":"54545433332","contact_api_id":"137","first_name":"John' .
                '","last_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"ci' .
                'ty":"Novi","state":"Michigan","postal_code":"48375","country":"US"},"company_na' .
                'me":"Fortis Payment Systems, LLC","header_message":"This is a sample message fo' .
                'r you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339' .
                '998822","office_phone":"3339998822","office_phone_ext":"5","header_message_type' .
                '":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3' .
                '":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com"' .
                ',"token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","' .
                'created_ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","received_emails":[{"subject":"Payment Receipt - 12' .
                'skiestech","body":"This email is being sent from a server.","source_address":"' .
                '\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestec' .
                'h A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-' .
                '8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","rea' .
                'son_sent":"Contact Email","reason_model":"Transaction","reason_model_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11' .
                'e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"is_deletable":true,"location' .
                '":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204' .
                '0992,"account_number":"5454545454545454","address":{"city":"Novi","state":"MI",' .
                '"postal_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e0' .
                '93242bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domai' .
                'n.com","fax":"3339998822","location_api_id":"location-111111","location_api_key' .
                '":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2",' .
                '"location_c3":"custom data 3","name":"Sample Company Headquarters","office_phon' .
                'e":"2481234567","office_ext_phone":"1021021209","tz":"America/New_York","parent' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":' .
                'true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","t' .
                'icket_hash_key":"A5F443CADF4AE34BBCAADF4"},"user":{"account_number":"5454545454' .
                '545454","branding_domain_url":"{branding_domain_url}","cell_phone":"3339998822"' .
                ',"company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","ema' .
                'il":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998822","firs' .
                't_name":"John","last_name":"Smith","locale":"en-US","office_phone":"3339998822"' .
                ',"office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requi' .
                'res_new_password":null,"terms_condition_code":"20220308","tz":"America/New_York' .
                '","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type":"csv"' .
                ',"process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f' .
                '1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_' .
                'key":null,"user_type_code":100,"password":null,"zip":"48375","location_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false,"' .
                'address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":14' .
                '22040992,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.16' .
                '8.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login":14220409' .
                '92,"log_api_response_body_ts":1422040992},"recurrings":[{"account_vault_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","token_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","account_vault_api_id":"token1234abcd","token_api_id":"t' .
                'oken1234abcd","_joi":{"conditions":{}},"active":true,"description":"Description' .
                '","end_date":"2021-12-01","installment_total_count":20,"interval":1,"interval_t' .
                'ype":"d","location_id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"paymen' .
                't_method":"cc","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","recurring_api_id":"recurring1234abcd","start_dat' .
                'e":"2021-12-01","status":"active","transaction_amount":300,"terms_agree":true,"' .
                'terms_agree_ip":"192.168.0.10","recurring_c1":"recurring custom data 1","recurr' .
                'ing_c2":"recurring custom data 2","recurring_c3":"recurring custom data 3","sen' .
                'd_to_proc_as_recur":true,"tags":["Walk-in Customer"],"secondary_amount":100,"cu' .
                'rrency":"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","cre' .
                'ated_ts":1422040992,"modified_ts":1422040992,"recurring_type_id":"i","installme' .
                'nt_amount_total":99999999,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"email' .
                '_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":true,"detail":true' .
                ',"created_ts":1422040992},"sms_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isB' .
                'lacklisted":true,"detail":true,"created_ts":1422040992},"changelogs":[{"id":"11' .
                'e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"Tran' .
                'sactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"' .
                'user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_nam' .
                'e":"Bob","last_name":"Fairview"}}],"postback_logs":[{"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","postback_config_id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","next_run_ts":1422040992,"created_ts":1422040992,"model_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a"}],"created_user":{"account_number":"5454545454545454",' .
                '"branding_domain_url":"{branding_domain_url}","cell_phone":"3339998822","compan' .
                'y_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"ema' .
                'il@domain.com","email_trx_receipt":true,"home_phone":"3339998822","first_name":' .
                '"John","last_name":"Smith","locale":"en-US","office_phone":"3339998822","office' .
                '_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_' .
                'password":null,"terms_condition_code":"20220308","tz":"America/New_York","ui_pr' .
                'efs":{"entry_page":"dashboard","page_size":2,"report_export_type":"csv","proces' .
                's_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"us' .
                'ername":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":nul' .
                'l,"user_type_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false,"address"' .
                ':{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f' .
                '8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992' .
                ',"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10",' .
                '"current_date_time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_' .
                'api_response_body_ts":1422040992},"parent":{"location_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","account_number":"54545433332","contact_api_id":"137","first_name":"John"' .
                ',"last_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"cit' .
                'y":"Novi","state":"Michigan","postal_code":"48375","country":"US"},"company_nam' .
                'e":"Fortis Payment Systems, LLC","header_message":"This is a sample message for' .
                ' you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"33399' .
                '98822","office_phone":"3339998822","office_phone_ext":"5","header_message_type"' .
                ':0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3"' .
                ':"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com",' .
                '"token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","c' .
                'reated_ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id":' .
                '"11e95f8ec39de8fbdb0a4f1a"},"children":{"location_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","account_number":"54545433332","contact_api_id":"137","first_name":"John","la' .
                'st_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city":"' .
                'Novi","state":"Michigan","postal_code":"48375","country":"US"},"company_name":"' .
                'Fortis Payment Systems, LLC","header_message":"This is a sample message for you' .
                '","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999882' .
                '2","office_phone":"3339998822","office_phone_ext":"5","header_message_type":0,"' .
                'update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"so' .
                'mething","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","tok' .
                'en_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","creat' .
                'ed_ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id":"11e' .
                '95f8ec39de8fbdb0a4f1a"}}],"links":{"type":"Links","first":"/v1/endpoint?page[si' .
                'ze]=10&page[number]=1","previous":"/v1/endpoint?page[size]=10&page[number]=5","' .
                'next":"/v1/endpoint?page[size]=10&page[number]=7","last":"/v1/endpoint?page[siz' .
                'e]=10&page[number]=42"},"pagination":{"type":"Pagination","total_count":423,"pa' .
                'ge_count":42,"page_number":6,"page_size":10},"sort":{"type":"Sorting","fields":' .
                '[{"field":"last_name","order":"asc"}]}}'
            )))
            ->assert();
    }

    public function testListAllContacts()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllContacts(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"ContactsCollection","list":[{"location_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"account_number":"54545433332","contact_api_id":"137","first_name":"John","las' .
                't_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city":"N' .
                'ovi","state":"Michigan","postal_code":"48375","country":"US"},"company_name":"F' .
                'ortis Payment Systems, LLC","header_message":"This is a sample message for you"' .
                ',"date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822' .
                '","office_phone":"3339998822","office_phone_ext":"5","header_message_type":0,"u' .
                'pdate_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"som' .
                'ething","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","toke' .
                'n_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","create' .
                'd_ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","received_emails":[{"subject":"Payment Receipt - 12skiest' .
                'ech","body":"This email is being sent from a server.","source_address":"\\"12sk' .
                'iestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3q' .
                'i\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a' .
                '5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sen' .
                't":"Contact Email","reason_model":"Transaction","reason_model_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec' .
                '39de8fbdb0a4f1a","created_ts":1422040992}],"is_deletable":true,"location":{"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"a' .
                'ccount_number":"5454545454545454","address":{"city":"Novi","state":"MI","postal' .
                '_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242bb' .
                '2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domain.com",' .
                '"fax":"3339998822","location_api_id":"location-111111","location_api_key":"AE34' .
                'BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","locati' .
                'on_c3":"custom data 3","name":"Sample Company Headquarters","office_phone":"248' .
                '1234567","office_ext_phone":"1021021209","tz":"America/New_York","parent_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":true,"c' .
                'reated_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","ticket_h' .
                'ash_key":"A5F443CADF4AE34BBCAADF4"},"user":{"account_number":"5454545454545454"' .
                ',"branding_domain_url":"{branding_domain_url}","cell_phone":"3339998822","compa' .
                'ny_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"em' .
                'ail@domain.com","email_trx_receipt":true,"home_phone":"3339998822","first_name"' .
                ':"John","last_name":"Smith","locale":"en-US","office_phone":"3339998822","offic' .
                'e_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new' .
                '_password":null,"terms_condition_code":"20220308","tz":"America/New_York","ui_p' .
                'refs":{"entry_page":"dashboard","page_size":2,"report_export_type":"csv","proce' .
                'ss_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"u' .
                'sername":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":nu' .
                'll,"user_type_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false,"address' .
                '":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":142204099' .
                '2,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10"' .
                ',"current_date_time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log' .
                '_api_response_body_ts":1422040992},"recurrings":[{"account_vault_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","token_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","account_vault_api_id":"token1234abcd","token_api_id":"token123' .
                '4abcd","_joi":{"conditions":{}},"active":true,"description":"Description","end_' .
                'date":"2021-12-01","installment_total_count":20,"interval":1,"interval_type":"d' .
                '","location_id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"payment_metho' .
                'd":"cc","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","recurring_api_id":"recurring1234abcd","start_date":"202' .
                '1-12-01","status":"active","transaction_amount":300,"terms_agree":true,"terms_a' .
                'gree_ip":"192.168.0.10","recurring_c1":"recurring custom data 1","recurring_c2"' .
                ':"recurring custom data 2","recurring_c3":"recurring custom data 3","send_to_pr' .
                'oc_as_recur":true,"tags":["Walk-in Customer"],"secondary_amount":100,"currency"' .
                ':"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","created_ts' .
                '":1422040992,"modified_ts":1422040992,"recurring_type_id":"i","installment_amou' .
                'nt_total":99999999,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"email_blackl' .
                'ist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":true,"detail":true,"creat' .
                'ed_ts":1422040992},"sms_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklis' .
                'ted":true,"detail":true,"created_ts":1422040992},"changelogs":[{"id":"11e95f8ec' .
                '39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"Transaction' .
                'Request","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"user":{' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_name":"Bob' .
                '","last_name":"Fairview"}}],"postback_logs":[{"id":"11e95f8ec39de8fbdb0a4f1a","' .
                'postback_config_id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fb' .
                'db0a4f1a","next_run_ts":1422040992,"created_ts":1422040992,"model_id":"11e95f8e' .
                'c39de8fbdb0a4f1a"}],"created_user":{"account_number":"5454545454545454","brandi' .
                'ng_domain_url":"{branding_domain_url}","cell_phone":"3339998822","company_name"' .
                ':"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of' .
                '_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@doma' .
                'in.com","email_trx_receipt":true,"home_phone":"3339998822","first_name":"John",' .
                '"last_name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_ph' .
                'one":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_passwor' .
                'd":null,"terms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"' .
                'entry_page":"dashboard","page_size":2,"report_export_type":"csv","process_metho' .
                'd":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username"' .
                ':"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user' .
                '_type_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","status_code":1,"api_only":false,"is_invitation":false,"address":{"city' .
                '":"Novi","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de' .
                '8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992,"creat' .
                'ed_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","curren' .
                't_date_time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_res' .
                'ponse_body_ts":1422040992},"parent":{"location_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'account_number":"54545433332","contact_api_id":"137","first_name":"John","last_' .
                'name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city":"Nov' .
                'i","state":"Michigan","postal_code":"48375","country":"US"},"company_name":"For' .
                'tis Payment Systems, LLC","header_message":"This is a sample message for you","' .
                'date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822",' .
                '"office_phone":"3339998822","office_phone_ext":"5","header_message_type":0,"upd' .
                'ate_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"somet' .
                'hing","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","token_' .
                'import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_' .
                'ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id":"11e95f' .
                '8ec39de8fbdb0a4f1a"},"children":{"location_id":"11e95f8ec39de8fbdb0a4f1a","acco' .
                'unt_number":"54545433332","contact_api_id":"137","first_name":"John","last_name' .
                '":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","' .
                'state":"Michigan","postal_code":"48375","country":"US"},"company_name":"Fortis ' .
                'Payment Systems, LLC","header_message":"This is a sample message for you","date' .
                '_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","off' .
                'ice_phone":"3339998822","office_phone_ext":"5","header_message_type":0,"update_' .
                'if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something' .
                '","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","token_impo' .
                'rt_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":' .
                '1422040992,"modified_ts":1422040992,"active":true,"created_user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a"}}],"links":{"type":"Links","first":"/v1/endpoint?page[size]=10&' .
                'page[number]=1","previous":"/v1/endpoint?page[size]=10&page[number]=5","next":"' .
                '/v1/endpoint?page[size]=10&page[number]=7","last":"/v1/endpoint?page[size]=10&p' .
                'age[number]=42"},"pagination":{"type":"Pagination","total_count":423,"page_coun' .
                't":42,"page_number":6,"page_size":10},"sort":{"type":"Sorting","fields":[{"fiel' .
                'd":"last_name","order":"asc"}]}}'
            )))
            ->assert();
    }

    public function testDeleteContact()
    {
        // Parameters for the API call
        $contactId = '11e95f8ec39de8fbdb0a4f1a';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->deleteContact($contactId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(204)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Contact","data":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_nu' .
                'mber":"54545433332","contact_api_id":"137","first_name":"John","last_name":"Smi' .
                'th","cell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","state"' .
                ':"Michigan","postal_code":"48375","country":"US"},"company_name":"Fortis Paymen' .
                't Systems, LLC","header_message":"This is a sample message for you","date_of_bi' .
                'rth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_ph' .
                'one":"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exi' .
                'sts":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","par' .
                'ent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","token_import_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204' .
                '0992,"modified_ts":1422040992,"active":true,"created_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a","received_emails":[{"subject":"Payment Receipt - 12skiestech","body":' .
                '"This email is being sent from a server.","source_address":"\\"12skiestech A7t3' .
                'qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3qi\\" <norepl' .
                'y@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d5' .
                '1c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sent":"Contact ' .
                'Email","reason_model":"Transaction","reason_model_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992}],"is_deletable":true,"location":{"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"account_numbe' .
                'r":"5454545454545454","address":{"city":"Novi","state":"MI","postal_code":"4837' .
                '5","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_ema' .
                'il_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242bb2","default_' .
                'cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domain.com","fax":"33399' .
                '98822","location_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34' .
                'BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","location_c3":"cust' .
                'om data 3","name":"Sample Company Headquarters","office_phone":"2481234567","of' .
                'fice_ext_phone":"1021021209","tz":"America/New_York","parent_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":true,"created_user_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","ticket_hash_key":"A5' .
                'F443CADF4AE34BBCAADF4"},"user":{"account_number":"5454545454545454","branding_d' .
                'omain_url":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fo' .
                'rtis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_bir' .
                'th":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.c' .
                'om","email_trx_receipt":true,"home_phone":"3339998822","first_name":"John","las' .
                't_name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone"' .
                ':"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":n' .
                'ull,"terms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entr' .
                'y_page":"dashboard","page_size":2,"report_export_type":"csv","process_method":"' .
                'virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{u' .
                'ser_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_typ' .
                'e_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","status_code":1,"api_only":false,"is_invitation":false,"address":{"city":"N' .
                'ovi","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbd' .
                'b0a4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992,"created_t' .
                's":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_da' .
                'te_time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_respons' .
                'e_body_ts":1422040992},"recurrings":[{"account_vault_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","token_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","account_vault_api_id":"token1234abcd","token_api_id":"token1234abcd","_joi' .
                '":{"conditions":{}},"active":true,"description":"Description","end_date":"2021-' .
                '12-01","installment_total_count":20,"interval":1,"interval_type":"d","location_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"payment_method":"cc","pro' .
                'duct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","recurring_api_id":"recurring1234abcd","start_date":"2021-12-01","st' .
                'atus":"active","transaction_amount":300,"terms_agree":true,"terms_agree_ip":"19' .
                '2.168.0.10","recurring_c1":"recurring custom data 1","recurring_c2":"recurring ' .
                'custom data 2","recurring_c3":"recurring custom data 3","send_to_proc_as_recur"' .
                ':true,"tags":["Walk-in Customer"],"secondary_amount":100,"currency":"USD","id":' .
                '"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","created_ts":1422040992' .
                ',"modified_ts":1422040992,"recurring_type_id":"i","installment_amount_total":99' .
                '999999,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"email_blacklist":{"id":"' .
                '11e95f8ec39de8fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts":14220' .
                '40992},"sms_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":true,"d' .
                'etail":true,"created_ts":1422040992},"changelogs":[{"id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992,"action":"CREATE","model":"TransactionRequest","mo' .
                'del_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","change' .
                'log_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fb' .
                'db0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"user":{"id":"11e95f' .
                '8ec39de8fbdb0a4f1a","username":"email@domain.com","first_name":"Bob","last_name' .
                '":"Fairview"}}],"postback_logs":[{"id":"11e95f8ec39de8fbdb0a4f1a","postback_con' .
                'fig_id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","n' .
                'ext_run_ts":1422040992,"created_ts":1422040992,"model_id":"11e95f8ec39de8fbdb0a' .
                '4f1a"}],"created_user":{"account_number":"5454545454545454","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fortis Pay' .
                'ment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"202' .
                '1-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","ema' .
                'il_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last_name":' .
                '"Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","pr' .
                'imary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"ter' .
                'ms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":' .
                '"dashboard","page_size":2,"report_export_type":"csv","process_method":"virtual_' .
                'terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name' .
                '}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":' .
                '100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","sta' .
                'tus_code":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","st' .
                'ate":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":14220' .
                '40992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","te' .
                'rms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time"' .
                ':"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_t' .
                's":1422040992},"parent":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_numb' .
                'er":"54545433332","contact_api_id":"137","first_name":"John","last_name":"Smith' .
                '","cell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","state":"' .
                'Michigan","postal_code":"48375","country":"US"},"company_name":"Fortis Payment ' .
                'Systems, LLC","header_message":"This is a sample message for you","date_of_birt' .
                'h":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phon' .
                'e":"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exist' .
                's":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","paren' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","token_import_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"modified_ts":1422040992,"active":true,"created_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a"},"children":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_number":' .
                '"54545433332","contact_api_id":"137","first_name":"John","last_name":"Smith","c' .
                'ell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","state":"Mich' .
                'igan","postal_code":"48375","country":"US"},"company_name":"Fortis Payment Syst' .
                'ems, LLC","header_message":"This is a sample message for you","date_of_birth":"' .
                '2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phone":"' .
                '3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exists":1' .
                ',"contact_c1":"any","contact_c2":"anything","contact_c3":"something","parent_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","token_import_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"' .
                'modified_ts":1422040992,"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a"}}}'
            )))
            ->assert();
    }

    public function testViewSingleContact()
    {
        // Parameters for the API call
        $contactId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleContact($contactId, $expand, $fields);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Contact","data":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_nu' .
                'mber":"54545433332","contact_api_id":"137","first_name":"John","last_name":"Smi' .
                'th","cell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","state"' .
                ':"Michigan","postal_code":"48375","country":"US"},"company_name":"Fortis Paymen' .
                't Systems, LLC","header_message":"This is a sample message for you","date_of_bi' .
                'rth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_ph' .
                'one":"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exi' .
                'sts":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","par' .
                'ent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","token_import_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204' .
                '0992,"modified_ts":1422040992,"active":true,"created_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a","received_emails":[{"subject":"Payment Receipt - 12skiestech","body":' .
                '"This email is being sent from a server.","source_address":"\\"12skiestech A7t3' .
                'qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3qi\\" <norepl' .
                'y@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d5' .
                '1c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sent":"Contact ' .
                'Email","reason_model":"Transaction","reason_model_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992}],"is_deletable":true,"location":{"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"account_numbe' .
                'r":"5454545454545454","address":{"city":"Novi","state":"MI","postal_code":"4837' .
                '5","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_ema' .
                'il_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242bb2","default_' .
                'cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domain.com","fax":"33399' .
                '98822","location_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34' .
                'BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","location_c3":"cust' .
                'om data 3","name":"Sample Company Headquarters","office_phone":"2481234567","of' .
                'fice_ext_phone":"1021021209","tz":"America/New_York","parent_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":true,"created_user_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","ticket_hash_key":"A5' .
                'F443CADF4AE34BBCAADF4"},"user":{"account_number":"5454545454545454","branding_d' .
                'omain_url":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fo' .
                'rtis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_bir' .
                'th":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.c' .
                'om","email_trx_receipt":true,"home_phone":"3339998822","first_name":"John","las' .
                't_name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone"' .
                ':"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":n' .
                'ull,"terms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entr' .
                'y_page":"dashboard","page_size":2,"report_export_type":"csv","process_method":"' .
                'virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{u' .
                'ser_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_typ' .
                'e_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","status_code":1,"api_only":false,"is_invitation":false,"address":{"city":"N' .
                'ovi","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbd' .
                'b0a4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992,"created_t' .
                's":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_da' .
                'te_time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_respons' .
                'e_body_ts":1422040992},"recurrings":[{"account_vault_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","token_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","account_vault_api_id":"token1234abcd","token_api_id":"token1234abcd","_joi' .
                '":{"conditions":{}},"active":true,"description":"Description","end_date":"2021-' .
                '12-01","installment_total_count":20,"interval":1,"interval_type":"d","location_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"payment_method":"cc","pro' .
                'duct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","recurring_api_id":"recurring1234abcd","start_date":"2021-12-01","st' .
                'atus":"active","transaction_amount":300,"terms_agree":true,"terms_agree_ip":"19' .
                '2.168.0.10","recurring_c1":"recurring custom data 1","recurring_c2":"recurring ' .
                'custom data 2","recurring_c3":"recurring custom data 3","send_to_proc_as_recur"' .
                ':true,"tags":["Walk-in Customer"],"secondary_amount":100,"currency":"USD","id":' .
                '"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","created_ts":1422040992' .
                ',"modified_ts":1422040992,"recurring_type_id":"i","installment_amount_total":99' .
                '999999,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"email_blacklist":{"id":"' .
                '11e95f8ec39de8fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts":14220' .
                '40992},"sms_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":true,"d' .
                'etail":true,"created_ts":1422040992},"changelogs":[{"id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992,"action":"CREATE","model":"TransactionRequest","mo' .
                'del_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","change' .
                'log_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fb' .
                'db0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"user":{"id":"11e95f' .
                '8ec39de8fbdb0a4f1a","username":"email@domain.com","first_name":"Bob","last_name' .
                '":"Fairview"}}],"postback_logs":[{"id":"11e95f8ec39de8fbdb0a4f1a","postback_con' .
                'fig_id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","n' .
                'ext_run_ts":1422040992,"created_ts":1422040992,"model_id":"11e95f8ec39de8fbdb0a' .
                '4f1a"}],"created_user":{"account_number":"5454545454545454","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fortis Pay' .
                'ment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"202' .
                '1-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","ema' .
                'il_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last_name":' .
                '"Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","pr' .
                'imary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"ter' .
                'ms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":' .
                '"dashboard","page_size":2,"report_export_type":"csv","process_method":"virtual_' .
                'terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name' .
                '}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":' .
                '100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","sta' .
                'tus_code":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","st' .
                'ate":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":14220' .
                '40992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","te' .
                'rms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time"' .
                ':"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_t' .
                's":1422040992},"parent":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_numb' .
                'er":"54545433332","contact_api_id":"137","first_name":"John","last_name":"Smith' .
                '","cell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","state":"' .
                'Michigan","postal_code":"48375","country":"US"},"company_name":"Fortis Payment ' .
                'Systems, LLC","header_message":"This is a sample message for you","date_of_birt' .
                'h":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phon' .
                'e":"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exist' .
                's":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","paren' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","token_import_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"modified_ts":1422040992,"active":true,"created_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a"},"children":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_number":' .
                '"54545433332","contact_api_id":"137","first_name":"John","last_name":"Smith","c' .
                'ell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","state":"Mich' .
                'igan","postal_code":"48375","country":"US"},"company_name":"Fortis Payment Syst' .
                'ems, LLC","header_message":"This is a sample message for you","date_of_birth":"' .
                '2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phone":"' .
                '3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exists":1' .
                ',"contact_c1":"any","contact_c2":"anything","contact_c3":"something","parent_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","token_import_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"' .
                'modified_ts":1422040992,"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a"}}}'
            )))
            ->assert();
    }
}
