<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\RecurringController;
use FortisAPILib\Exceptions;

class RecurringControllerTest extends BaseTestController
{
    /**
     * @var RecurringController RecurringController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getRecurringController();
    }

    public function testListAllRecurringRecord()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllRecurringRecord(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"RecurringsCollection","list":[{"account_vault_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","token_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","account_vault_api_id":"token1234abcd","token_api_id":"token1234abcd","_' .
                'joi":{"conditions":{}},"active":true,"description":"Description","end_date":"20' .
                '21-12-01","installment_total_count":20,"interval":1,"interval_type":"d","locati' .
                'on_id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"payment_method":"cc","' .
                'product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","recurring_api_id":"recurring1234abcd","start_date":"2021-12-01",' .
                '"status":"active","transaction_amount":300,"terms_agree":true,"terms_agree_ip":' .
                '"192.168.0.10","recurring_c1":"recurring custom data 1","recurring_c2":"recurri' .
                'ng custom data 2","recurring_c3":"recurring custom data 3","send_to_proc_as_rec' .
                'ur":true,"tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal' .
                '","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040' .
                '992}],"secondary_amount":100,"currency":"USD","id":"11e95f8ec39de8fbdb0a4f1a","' .
                'next_run_date":"2021-12-01","created_ts":1422040992,"modified_ts":1422040992,"r' .
                'ecurring_type_id":"i","installment_amount_total":99999999,"created_user_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","log_emails":[{"subject":"Payment Receipt - 12skiestech' .
                '","body":"This email is being sent from a server.","source_address":"\\"12skies' .
                'tech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3qi' .
                '\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a5' .
                'b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sent' .
                '":"Contact Email","reason_model":"Transaction","reason_model_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"location_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137","first_nam' .
                'e":"John","last_name":"Smith","cell_phone":"3339998822","balance":245.36,"addre' .
                'ss":{"city":"Novi","state":"Michigan","postal_code":"48375","country":"US"},"co' .
                'mpany_name":"Fortis Payment Systems, LLC","header_message":"This is a sample me' .
                'ssage for you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phon' .
                'e":"3339998822","office_phone":"3339998822","office_phone_ext":"5","header_mess' .
                'age_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anything","co' .
                'ntact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@dom' .
                'ain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0' .
                'a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true,"created_' .
                'user_id":"11e95f8ec39de8fbdb0a4f1a"},"account_vault":{"account_holder_name":"Jo' .
                'hn Smith","account_vault_api_id":"accountvaultabcd","token_api_id":"tokenabcd",' .
                '"accountvault_c1":"accountvault custom 1","accountvault_c2":"accountvault custo' .
                'm 2","accountvault_c3":"accountvault custom 3","token_c1":"token custom 1","tok' .
                'en_c2":"token custom 2","token_c3":"token custom 3","ach_sec_code":"WEB","billi' .
                'ng_address":{"city":"Novi","state":"Michigan","postal_code":"48375","phone":"33' .
                '39998822","country":"USA"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id' .
                '":"123456","identity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4' .
                '":"8527","dob_year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_' .
                'account_vault_api_id":"previousaccountvault123456","previous_token_api_id":"pre' .
                'viousaccountvault123456","previous_account_vault_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"previous_token_id":"11e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","account_number":"545454545454545","terms_agree":true,"te' .
                'rms_agree_ip":"192.168.0.10","title":"Test CC Account","token_import_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","secure_directory_server_transaction_id":"d65e93c3-35ab-41' .
                'ba-b307-767bfc19eae","secure_protocol_version":2,"secure_auth_data":"vVwL7UNHCf' .
                '8W8M2LAfvRChNHN7c%3D","secure_collection_indicator":null,"three_ds_server_trans' .
                '_id":"d65e93c3-35ab-41ba-b307-767bfc19eae","acs_transaction_id":"13c701a3-5a88-' .
                '4c45-89e9-ef65e50a8bf9","_joi":{},"id":"11e95f8ec39de8fbdb0a4f1a","account_type' .
                '":"checking","active":true,"cau_summary_status_id":1,"created_ts":1422040992,"e' .
                '_serial_number":"1234567890","e_track_data":null,"e_format":null,"e_keyed_data"' .
                ':null,"expiring_in_months":null,"exp_date":"0722","first_six":"700953","has_rec' .
                'urring":false,"last_four":"3657","modified_ts":1422040992,"payment_method":"cc"' .
                ',"ticket":null,"track_data":null,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'cau_last_updated_ts":1422040992,"routing_number":"051904524"},"created_user":{"' .
                'account_number":"5454545454545454","branding_domain_url":"{branding_domain_url}' .
                '","cell_phone":"3339998822","company_name":"Fortis Payment Systems, LLC","conta' .
                'ct_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"hom' .
                'e_phone":"3339998822","first_name":"John","last_name":"Smith","locale":"en-US",' .
                '"office_phone":"3339998822","office_ext_phone":"5","primary_location_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_condition_code":"20220' .
                '308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2' .
                ',"report_export_type":"csv","process_method":"virtual_terminal","default_termin' .
                'al":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas' .
                '8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"password":null,"zip"' .
                ':"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":fa' .
                'lse,"is_invitation":false,"address":{"city":"Novi","state":"MI","postal_code":"' .
                '48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_att' .
                'empts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_ts":14220' .
                '40992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":14220409' .
                '92,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-070' .
                '0","current_login":1422040992,"log_api_response_body_ts":1422040992},"signature' .
                '":{"signature":"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAACvklEQVR4nO3bLZO' .
                'qUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIXtaXw2H3/5s5MwZ39rgz/zkvuK' .
                'Kqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6WCxURDTLsqmngzcgOMdtNhsVE' .
                'RURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiC' .
                'q6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4' .
                'D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b4NLU3T9jVbTLcRnMO620ezep1Op3bF83' .
                '2/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBT' .
                'eBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRW' .
                'wVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7p' .
                'tt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz78' .
                'cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpq' .
                'nVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEcYBHBARYRHGARwQEW' .
                'ERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+EC0ah++pNrAAAAAElFTkSuQmC' .
                'C","resource":"Transaction","resource_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992},"paymen' .
                't_schedule":["2021-12-01"],"location":{"id":"11e95f8ec39de8fbdb0a4f1a","created' .
                '_ts":1422040992,"modified_ts":1422040992,"account_number":"5454545454545454","a' .
                'ddress":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"bran' .
                'ding_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":' .
                'true,"default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e0922' .
                '42dda","email_reply_to":"email@domain.com","fax":"3339998822","location_api_id"' .
                ':"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":' .
                '"custom 1","location_c2":"custom 2","location_c3":"custom data 3","name":"Sampl' .
                'e Company Headquarters","office_phone":"2481234567","office_ext_phone":"1021021' .
                '209","tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_conta' .
                'ct_notes":true,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","location_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},' .
                '"product_transaction":{"processor_version":"1_0_0","title":"My terminal","payme' .
                'nt_method":"cc","processor":"zgate","mcc":"1111","tax_surcharge_config":2,"part' .
                'ner":"standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"proc' .
                'essor_data":{},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_tip":t' .
                'rue,"ach_allow_debit":true,"ach_allow_credit":true,"ach_allow_refund":true,"vt_' .
                'cvv":true,"vt_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":true,"' .
                'receipt_show_contact_name":true,"display_avs":true,"card_type_visa":true,"card_' .
                'type_mc":true,"card_type_disc":true,"card_type_amex":true,"card_type_diners":tr' .
                'ue,"card_type_jcb":true,"card_type_ebt":true,"allow_ebt_cash_benefit":true,"all' .
                'ow_ebt_food_stamp":true,"invoice_location":true,"allow_partial_authorization":t' .
                'rue,"allow_recurring_partial_authorization":true,"auto_decline_cvv":true,"auto_' .
                'decline_street":true,"auto_decline_zip":true,"split_payments_allow":true,"vt_sh' .
                'ow_custom_fields":true,"receipt_show_custom_fields":true,"vt_override_sales_tax' .
                '_allowed":true,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_require_str' .
                'eet":true,"auto_decline_cavv":true,"current_batch":34,"dup_check_per_batch":nul' .
                'l,"paylink_allow":false,"quick_invoice_allow":false,"level3_allow":false,"payfa' .
                'c_enable":false,"enable_3ds":false,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"hosted_payment_page_allow":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","a' .
                'llow_big_commerce":false,"level3_default":{"destination_country_code":"840","du' .
                'ty_amount":0,"freight_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_' .
                'code":"AZ12345","shipto_zip_code":"MI48335","tax_amount":0,"tax_exempt":"0","cu' .
                'stomer_vat_registration":"12345678","merchant_vat_registration":"123456","order' .
                '_date":"171006","summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_nu' .
                'mber":"vat1234","line_items":[{"alternate_tax_id":"1234","debit_credit":"C","de' .
                'scription":"cool drink","discount_amount":10,"discount_rate":11,"product_code":' .
                '"coke12345678","quantity":5,"tax_amount":3,"tax_rate":0,"tax_type_applied":"22"' .
                ',"tax_type_id":"a1","unit_code":"gll","unit_cost":10,"commodity_code":"cc123456' .
                '","other_tax_amount":0}]},"cau_subscribe_type_id":0,"location_billing_account_i' .
                'd":"11eb88b873980c64a21e5fd2","product_billing_group_id":"nofees","account_numb' .
                'er":"12345678","run_avs_on_accountvault_create":false,"accountvault_expire_noti' .
                'fication_email_enable":false,"debit_allow_void":false,"quick_invoice_text_to_pa' .
                'y":false,"sms_enable":false,"vt_show_currency":true,"receipt_show_currency":fal' .
                'se,"allow_blind_refund":false,"vt_show_company_name":false,"receipt_show_compan' .
                'y_name":false,"bank_funded_only":false,"require_cvv_on_keyed_cnp":true,"require' .
                '_cvv_on_tokenized_cnp":true,"show_secondary_amount":false,"allow_secondary_amou' .
                'nt":false,"show_google_pay":true,"show_apple_pay":true,"batch_risk_config":{},"' .
                'currency_code":840,"enable_ach_validation":false,"enable_ach_retry":false,"id":' .
                '"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts":' .
                '1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","product_transaction_api_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"is_secondary_amount_allowed":false,"fortis_id":"8149742","product_billing_grou' .
                'p_code":"nofees","cau_subscribe_type_code":0},"next_run_date_min":"2021-12-01",' .
                '"next_run_date_max":"2021-12-01","all_tags":[{"location_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","title":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422' .
                '040992,"modified_ts":1422040992}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a' .
                '","created_ts":1422040992,"action":"CREATE","model":"TransactionRequest","model' .
                '_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog' .
                '_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","field":"next_run_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec' .
                '39de8fbdb0a4f1a","username":"email@domain.com","first_name":"Bob","last_name":"' .
                'Fairview"}}],"forecast":{"id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"Recurr' .
                'ing ID","created_ts":1422040992,"modified_ts":1422040992},"recurring_splits":[{' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a"}]}],"links":{"type":"Links","first":"/v1/endpoint?page[si' .
                'ze]=10&page[number]=1","previous":"/v1/endpoint?page[size]=10&page[number]=5","' .
                'next":"/v1/endpoint?page[size]=10&page[number]=7","last":"/v1/endpoint?page[siz' .
                'e]=10&page[number]=42"},"pagination":{"type":"Pagination","total_count":423,"pa' .
                'ge_count":42,"page_number":6,"page_size":10},"sort":{"type":"Sorting","fields":' .
                '[{"field":"last_name","order":"asc"}]}}'
            )))
            ->assert();
    }

    public function testDeleteRecurringRecord()
    {
        // Parameters for the API call
        $recurringId = '11e95f8ec39de8fbdb0a4f1a';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->deleteRecurringRecord($recurringId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(204)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Recurring","data":{"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","tok' .
                'en_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e95f8ec39de8fbdb0a4f1a","acco' .
                'unt_vault_api_id":"token1234abcd","token_api_id":"token1234abcd","_joi":{"condi' .
                'tions":{}},"active":true,"description":"Description","end_date":"2021-12-01","i' .
                'nstallment_total_count":20,"interval":1,"interval_type":"d","location_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","notification_days":2,"payment_method":"cc","product_tran' .
                'saction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","recurring_api_id":"recurring1234abcd","start_date":"2021-12-01","status":"ac' .
                'tive","transaction_amount":300,"terms_agree":true,"terms_agree_ip":"192.168.0.1' .
                '0","recurring_c1":"recurring custom data 1","recurring_c2":"recurring custom da' .
                'ta 2","recurring_c3":"recurring custom data 3","send_to_proc_as_recur":true,"ta' .
                'gs":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}],"secon' .
                'dary_amount":100,"currency":"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_dat' .
                'e":"2021-12-01","created_ts":1422040992,"modified_ts":1422040992,"recurring_typ' .
                'e_id":"i","installment_amount_total":99999999,"created_user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","log_emails":[{"subject":"Payment Receipt - 12skiestech","body":"Th' .
                'is email is being sent from a server.","source_address":"\\"12skiestech A7t3qi' .
                '\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3qi\\" <noreply@' .
                'zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c' .
                '4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sent":"Contact Em' .
                'ail","reason_model":"Transaction","reason_model_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec39de8fbdb0a4f1' .
                'a","created_ts":1422040992}],"contact":{"location_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","account_number":"54545433332","contact_api_id":"137","first_name":"John","la' .
                'st_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city":"' .
                'Novi","state":"Michigan","postal_code":"48375","country":"US"},"company_name":"' .
                'Fortis Payment Systems, LLC","header_message":"This is a sample message for you' .
                '","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999882' .
                '2","office_phone":"3339998822","office_phone_ext":"5","header_message_type":0,"' .
                'update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"so' .
                'mething","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","tok' .
                'en_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","creat' .
                'ed_ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id":"11e' .
                '95f8ec39de8fbdb0a4f1a"},"account_vault":{"account_holder_name":"John Smith","ac' .
                'count_vault_api_id":"accountvaultabcd","token_api_id":"tokenabcd","accountvault' .
                '_c1":"accountvault custom 1","accountvault_c2":"accountvault custom 2","account' .
                'vault_c3":"accountvault custom 3","token_c1":"token custom 1","token_c2":"token' .
                ' custom 2","token_c3":"token custom 3","ach_sec_code":"WEB","billing_address":{' .
                '"city":"Novi","state":"Michigan","postal_code":"48375","phone":"3339998822","co' .
                'untry":"USA"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","i' .
                'dentity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":"8527","dob' .
                '_year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault' .
                '_api_id":"previousaccountvault123456","previous_token_api_id":"previousaccountv' .
                'ault123456","previous_account_vault_id":"11e95f8ec39de8fbdb0a4f1a","previous_to' .
                'ken_id":"11e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","account_number":"545454545454545","terms_agree":true,"terms_agree_ip"' .
                ':"192.168.0.10","title":"Test CC Account","token_import_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","secure_directory_server_transaction_id":"d65e93c3-35ab-41ba-b307-767bf' .
                'c19eae","secure_protocol_version":2,"secure_auth_data":"vVwL7UNHCf8W8M2LAfvRChN' .
                'HN7c%3D","secure_collection_indicator":null,"three_ds_server_trans_id":"d65e93c' .
                '3-35ab-41ba-b307-767bfc19eae","acs_transaction_id":"13c701a3-5a88-4c45-89e9-ef6' .
                '5e50a8bf9","_joi":{},"id":"11e95f8ec39de8fbdb0a4f1a","account_type":"checking",' .
                '"active":true,"cau_summary_status_id":1,"created_ts":1422040992,"e_serial_numbe' .
                'r":"1234567890","e_track_data":null,"e_format":null,"e_keyed_data":null,"expiri' .
                'ng_in_months":null,"exp_date":"0722","first_six":"700953","has_recurring":false' .
                ',"last_four":"3657","modified_ts":1422040992,"payment_method":"cc","ticket":nul' .
                'l,"track_data":null,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","cau_last_upda' .
                'ted_ts":1422040992,"routing_number":"051904524"},"created_user":{"account_numbe' .
                'r":"5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phone' .
                '":"3339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fb' .
                'db0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"333' .
                '9998822","first_name":"John","last_name":"Smith","locale":"en-US","office_phone' .
                '":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"Am' .
                'erica/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_expo' .
                'rt_type":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8e' .
                'c39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w' .
                '2","user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","loc' .
                'ation_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invit' .
                'ation":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","count' .
                'ry":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"las' .
                't_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"create' .
                'd_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agr' .
                'ee_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_l' .
                'ogin":1422040992,"log_api_response_body_ts":1422040992},"signature":{"signature' .
                '":"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqN' .
                'RiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIXtaXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/' .
                'y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfek' .
                'p4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6' .
                'NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvD' .
                'sH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJz' .
                'jumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGB' .
                'rmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDG' .
                'rNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8Bsgsvz' .
                'XEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vb' .
                'v1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed' .
                '0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcY' .
                'BHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+EC0ah++pNrAAAAAElFTkSuQmCC","resource"' .
                ':"Transaction","resource_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbd' .
                'b0a4f1a","created_ts":1422040992,"modified_ts":1422040992},"payment_schedule":[' .
                '"2021-12-01"],"location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"modified_ts":1422040992,"account_number":"5454545454545454","address":{"cit' .
                'y":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default' .
                '_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email' .
                '_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"location-11' .
                '1111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","l' .
                'ocation_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Hea' .
                'dquarters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"Am' .
                'erica/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":tru' .
                'e,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","locat' .
                'ion_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"product_tran' .
                'saction":{"processor_version":"1_0_0","title":"My terminal","payment_method":"c' .
                'c","processor":"zgate","mcc":"1111","tax_surcharge_config":2,"partner":"standal' .
                'one","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{' .
                '},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allo' .
                'w_debit":true,"ach_allow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt' .
                '_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":true,"receipt_show_' .
                'contact_name":true,"display_avs":true,"card_type_visa":true,"card_type_mc":true' .
                ',"card_type_disc":true,"card_type_amex":true,"card_type_diners":true,"card_type' .
                '_jcb":true,"card_type_ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt_food_s' .
                'tamp":true,"invoice_location":true,"allow_partial_authorization":true,"allow_re' .
                'curring_partial_authorization":true,"auto_decline_cvv":true,"auto_decline_stree' .
                't":true,"auto_decline_zip":true,"split_payments_allow":true,"vt_show_custom_fie' .
                'lds":true,"receipt_show_custom_fields":true,"vt_override_sales_tax_allowed":tru' .
                'e,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_require_street":true,"au' .
                'to_decline_cavv":true,"current_batch":34,"dup_check_per_batch":null,"paylink_al' .
                'low":false,"quick_invoice_allow":false,"level3_allow":false,"payfac_enable":fal' .
                'se,"enable_3ds":false,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_paym' .
                'ent_page_allow":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_comm' .
                'erce":false,"level3_default":{"destination_country_code":"840","duty_amount":0,' .
                '"freight_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ1234' .
                '5","shipto_zip_code":"MI48335","tax_amount":0,"tax_exempt":"0","customer_vat_re' .
                'gistration":"12345678","merchant_vat_registration":"123456","order_date":"17100' .
                '6","summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat123' .
                '4","line_items":[{"alternate_tax_id":"1234","debit_credit":"C","description":"c' .
                'ool drink","discount_amount":10,"discount_rate":11,"product_code":"coke12345678' .
                '","quantity":5,"tax_amount":3,"tax_rate":0,"tax_type_applied":"22","tax_type_id' .
                '":"a1","unit_code":"gll","unit_cost":10,"commodity_code":"cc123456","other_tax_' .
                'amount":0}]},"cau_subscribe_type_id":0,"location_billing_account_id":"11eb88b87' .
                '3980c64a21e5fd2","product_billing_group_id":"nofees","account_number":"12345678' .
                '","run_avs_on_accountvault_create":false,"accountvault_expire_notification_emai' .
                'l_enable":false,"debit_allow_void":false,"quick_invoice_text_to_pay":false,"sms' .
                '_enable":false,"vt_show_currency":true,"receipt_show_currency":false,"allow_bli' .
                'nd_refund":false,"vt_show_company_name":false,"receipt_show_company_name":false' .
                ',"bank_funded_only":false,"require_cvv_on_keyed_cnp":true,"require_cvv_on_token' .
                'ized_cnp":true,"show_secondary_amount":false,"allow_secondary_amount":false,"sh' .
                'ow_google_pay":true,"show_apple_pay":true,"batch_risk_config":{},"currency_code' .
                '":840,"enable_ach_validation":false,"enable_ach_retry":false,"id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts":1422040992,"c' .
                'reated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a","product_transaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary' .
                '_amount_allowed":false,"fortis_id":"8149742","product_billing_group_code":"nofe' .
                'es","cau_subscribe_type_code":0},"next_run_date_min":"2021-12-01","next_run_dat' .
                'e_max":"2021-12-01","all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","titl' .
                'e":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modif' .
                'ied_ts":1422040992}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts' .
                '":1422040992,"action":"CREATE","model":"TransactionRequest","model_id":"11ec829' .
                '598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"' .
                'id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field' .
                '":"next_run_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f' .
                '1a","username":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}],' .
                '"forecast":{"id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"Recurring ID","crea' .
                'ted_ts":1422040992,"modified_ts":1422040992},"recurring_splits":[{"id":"11e95f8' .
                'ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbd' .
                'b0a4f1a"}]}}'
            )))
            ->assert();
    }

    public function testViewSingleRecurringRecord()
    {
        // Parameters for the API call
        $recurringId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleRecurringRecord($recurringId, $expand, $fields);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Recurring","data":{"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","tok' .
                'en_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e95f8ec39de8fbdb0a4f1a","acco' .
                'unt_vault_api_id":"token1234abcd","token_api_id":"token1234abcd","_joi":{"condi' .
                'tions":{}},"active":true,"description":"Description","end_date":"2021-12-01","i' .
                'nstallment_total_count":20,"interval":1,"interval_type":"d","location_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","notification_days":2,"payment_method":"cc","product_tran' .
                'saction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","recurring_api_id":"recurring1234abcd","start_date":"2021-12-01","status":"ac' .
                'tive","transaction_amount":300,"terms_agree":true,"terms_agree_ip":"192.168.0.1' .
                '0","recurring_c1":"recurring custom data 1","recurring_c2":"recurring custom da' .
                'ta 2","recurring_c3":"recurring custom data 3","send_to_proc_as_recur":true,"ta' .
                'gs":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}],"secon' .
                'dary_amount":100,"currency":"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_dat' .
                'e":"2021-12-01","created_ts":1422040992,"modified_ts":1422040992,"recurring_typ' .
                'e_id":"i","installment_amount_total":99999999,"created_user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","log_emails":[{"subject":"Payment Receipt - 12skiestech","body":"Th' .
                'is email is being sent from a server.","source_address":"\\"12skiestech A7t3qi' .
                '\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3qi\\" <noreply@' .
                'zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c' .
                '4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sent":"Contact Em' .
                'ail","reason_model":"Transaction","reason_model_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec39de8fbdb0a4f1' .
                'a","created_ts":1422040992}],"contact":{"location_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","account_number":"54545433332","contact_api_id":"137","first_name":"John","la' .
                'st_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city":"' .
                'Novi","state":"Michigan","postal_code":"48375","country":"US"},"company_name":"' .
                'Fortis Payment Systems, LLC","header_message":"This is a sample message for you' .
                '","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999882' .
                '2","office_phone":"3339998822","office_phone_ext":"5","header_message_type":0,"' .
                'update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"so' .
                'mething","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","tok' .
                'en_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","creat' .
                'ed_ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id":"11e' .
                '95f8ec39de8fbdb0a4f1a"},"account_vault":{"account_holder_name":"John Smith","ac' .
                'count_vault_api_id":"accountvaultabcd","token_api_id":"tokenabcd","accountvault' .
                '_c1":"accountvault custom 1","accountvault_c2":"accountvault custom 2","account' .
                'vault_c3":"accountvault custom 3","token_c1":"token custom 1","token_c2":"token' .
                ' custom 2","token_c3":"token custom 3","ach_sec_code":"WEB","billing_address":{' .
                '"city":"Novi","state":"Michigan","postal_code":"48375","phone":"3339998822","co' .
                'untry":"USA"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","i' .
                'dentity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":"8527","dob' .
                '_year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault' .
                '_api_id":"previousaccountvault123456","previous_token_api_id":"previousaccountv' .
                'ault123456","previous_account_vault_id":"11e95f8ec39de8fbdb0a4f1a","previous_to' .
                'ken_id":"11e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","account_number":"545454545454545","terms_agree":true,"terms_agree_ip"' .
                ':"192.168.0.10","title":"Test CC Account","token_import_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","secure_directory_server_transaction_id":"d65e93c3-35ab-41ba-b307-767bf' .
                'c19eae","secure_protocol_version":2,"secure_auth_data":"vVwL7UNHCf8W8M2LAfvRChN' .
                'HN7c%3D","secure_collection_indicator":null,"three_ds_server_trans_id":"d65e93c' .
                '3-35ab-41ba-b307-767bfc19eae","acs_transaction_id":"13c701a3-5a88-4c45-89e9-ef6' .
                '5e50a8bf9","_joi":{},"id":"11e95f8ec39de8fbdb0a4f1a","account_type":"checking",' .
                '"active":true,"cau_summary_status_id":1,"created_ts":1422040992,"e_serial_numbe' .
                'r":"1234567890","e_track_data":null,"e_format":null,"e_keyed_data":null,"expiri' .
                'ng_in_months":null,"exp_date":"0722","first_six":"700953","has_recurring":false' .
                ',"last_four":"3657","modified_ts":1422040992,"payment_method":"cc","ticket":nul' .
                'l,"track_data":null,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","cau_last_upda' .
                'ted_ts":1422040992,"routing_number":"051904524"},"created_user":{"account_numbe' .
                'r":"5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phone' .
                '":"3339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fb' .
                'db0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"333' .
                '9998822","first_name":"John","last_name":"Smith","locale":"en-US","office_phone' .
                '":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"Am' .
                'erica/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_expo' .
                'rt_type":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8e' .
                'c39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w' .
                '2","user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","loc' .
                'ation_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invit' .
                'ation":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","count' .
                'ry":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"las' .
                't_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"create' .
                'd_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agr' .
                'ee_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_l' .
                'ogin":1422040992,"log_api_response_body_ts":1422040992},"signature":{"signature' .
                '":"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqN' .
                'RiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIXtaXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/' .
                'y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfek' .
                'p4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6' .
                'NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvD' .
                'sH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJz' .
                'jumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGB' .
                'rmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDG' .
                'rNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8Bsgsvz' .
                'XEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vb' .
                'v1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed' .
                '0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcY' .
                'BHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+EC0ah++pNrAAAAAElFTkSuQmCC","resource"' .
                ':"Transaction","resource_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbd' .
                'b0a4f1a","created_ts":1422040992,"modified_ts":1422040992},"payment_schedule":[' .
                '"2021-12-01"],"location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"modified_ts":1422040992,"account_number":"5454545454545454","address":{"cit' .
                'y":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default' .
                '_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email' .
                '_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"location-11' .
                '1111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","l' .
                'ocation_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Hea' .
                'dquarters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"Am' .
                'erica/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":tru' .
                'e,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","locat' .
                'ion_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"product_tran' .
                'saction":{"processor_version":"1_0_0","title":"My terminal","payment_method":"c' .
                'c","processor":"zgate","mcc":"1111","tax_surcharge_config":2,"partner":"standal' .
                'one","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{' .
                '},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allo' .
                'w_debit":true,"ach_allow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt' .
                '_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":true,"receipt_show_' .
                'contact_name":true,"display_avs":true,"card_type_visa":true,"card_type_mc":true' .
                ',"card_type_disc":true,"card_type_amex":true,"card_type_diners":true,"card_type' .
                '_jcb":true,"card_type_ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt_food_s' .
                'tamp":true,"invoice_location":true,"allow_partial_authorization":true,"allow_re' .
                'curring_partial_authorization":true,"auto_decline_cvv":true,"auto_decline_stree' .
                't":true,"auto_decline_zip":true,"split_payments_allow":true,"vt_show_custom_fie' .
                'lds":true,"receipt_show_custom_fields":true,"vt_override_sales_tax_allowed":tru' .
                'e,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_require_street":true,"au' .
                'to_decline_cavv":true,"current_batch":34,"dup_check_per_batch":null,"paylink_al' .
                'low":false,"quick_invoice_allow":false,"level3_allow":false,"payfac_enable":fal' .
                'se,"enable_3ds":false,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_paym' .
                'ent_page_allow":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_comm' .
                'erce":false,"level3_default":{"destination_country_code":"840","duty_amount":0,' .
                '"freight_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ1234' .
                '5","shipto_zip_code":"MI48335","tax_amount":0,"tax_exempt":"0","customer_vat_re' .
                'gistration":"12345678","merchant_vat_registration":"123456","order_date":"17100' .
                '6","summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat123' .
                '4","line_items":[{"alternate_tax_id":"1234","debit_credit":"C","description":"c' .
                'ool drink","discount_amount":10,"discount_rate":11,"product_code":"coke12345678' .
                '","quantity":5,"tax_amount":3,"tax_rate":0,"tax_type_applied":"22","tax_type_id' .
                '":"a1","unit_code":"gll","unit_cost":10,"commodity_code":"cc123456","other_tax_' .
                'amount":0}]},"cau_subscribe_type_id":0,"location_billing_account_id":"11eb88b87' .
                '3980c64a21e5fd2","product_billing_group_id":"nofees","account_number":"12345678' .
                '","run_avs_on_accountvault_create":false,"accountvault_expire_notification_emai' .
                'l_enable":false,"debit_allow_void":false,"quick_invoice_text_to_pay":false,"sms' .
                '_enable":false,"vt_show_currency":true,"receipt_show_currency":false,"allow_bli' .
                'nd_refund":false,"vt_show_company_name":false,"receipt_show_company_name":false' .
                ',"bank_funded_only":false,"require_cvv_on_keyed_cnp":true,"require_cvv_on_token' .
                'ized_cnp":true,"show_secondary_amount":false,"allow_secondary_amount":false,"sh' .
                'ow_google_pay":true,"show_apple_pay":true,"batch_risk_config":{},"currency_code' .
                '":840,"enable_ach_validation":false,"enable_ach_retry":false,"id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts":1422040992,"c' .
                'reated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a","product_transaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary' .
                '_amount_allowed":false,"fortis_id":"8149742","product_billing_group_code":"nofe' .
                'es","cau_subscribe_type_code":0},"next_run_date_min":"2021-12-01","next_run_dat' .
                'e_max":"2021-12-01","all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","titl' .
                'e":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modif' .
                'ied_ts":1422040992}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts' .
                '":1422040992,"action":"CREATE","model":"TransactionRequest","model_id":"11ec829' .
                '598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"' .
                'id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field' .
                '":"next_run_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f' .
                '1a","username":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}],' .
                '"forecast":{"id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"Recurring ID","crea' .
                'ted_ts":1422040992,"modified_ts":1422040992},"recurring_splits":[{"id":"11e95f8' .
                'ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbd' .
                'b0a4f1a"}]}}'
            )))
            ->assert();
    }

    public function testActivateRecurringPayment()
    {
        // Parameters for the API call
        $recurringId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->activateRecurringPayment($recurringId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Recurring","data":{"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","tok' .
                'en_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e95f8ec39de8fbdb0a4f1a","acco' .
                'unt_vault_api_id":"token1234abcd","token_api_id":"token1234abcd","_joi":{"condi' .
                'tions":{}},"active":true,"description":"Description","end_date":"2021-12-01","i' .
                'nstallment_total_count":20,"interval":1,"interval_type":"d","location_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","notification_days":2,"payment_method":"cc","product_tran' .
                'saction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","recurring_api_id":"recurring1234abcd","start_date":"2021-12-01","status":"ac' .
                'tive","transaction_amount":300,"terms_agree":true,"terms_agree_ip":"192.168.0.1' .
                '0","recurring_c1":"recurring custom data 1","recurring_c2":"recurring custom da' .
                'ta 2","recurring_c3":"recurring custom data 3","send_to_proc_as_recur":true,"ta' .
                'gs":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}],"secon' .
                'dary_amount":100,"currency":"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_dat' .
                'e":"2021-12-01","created_ts":1422040992,"modified_ts":1422040992,"recurring_typ' .
                'e_id":"i","installment_amount_total":99999999,"created_user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","log_emails":[{"subject":"Payment Receipt - 12skiestech","body":"Th' .
                'is email is being sent from a server.","source_address":"\\"12skiestech A7t3qi' .
                '\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3qi\\" <noreply@' .
                'zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c' .
                '4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sent":"Contact Em' .
                'ail","reason_model":"Transaction","reason_model_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec39de8fbdb0a4f1' .
                'a","created_ts":1422040992}],"contact":{"location_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","account_number":"54545433332","contact_api_id":"137","first_name":"John","la' .
                'st_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city":"' .
                'Novi","state":"Michigan","postal_code":"48375","country":"US"},"company_name":"' .
                'Fortis Payment Systems, LLC","header_message":"This is a sample message for you' .
                '","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999882' .
                '2","office_phone":"3339998822","office_phone_ext":"5","header_message_type":0,"' .
                'update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"so' .
                'mething","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","tok' .
                'en_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","creat' .
                'ed_ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id":"11e' .
                '95f8ec39de8fbdb0a4f1a"},"account_vault":{"account_holder_name":"John Smith","ac' .
                'count_vault_api_id":"accountvaultabcd","token_api_id":"tokenabcd","accountvault' .
                '_c1":"accountvault custom 1","accountvault_c2":"accountvault custom 2","account' .
                'vault_c3":"accountvault custom 3","token_c1":"token custom 1","token_c2":"token' .
                ' custom 2","token_c3":"token custom 3","ach_sec_code":"WEB","billing_address":{' .
                '"city":"Novi","state":"Michigan","postal_code":"48375","phone":"3339998822","co' .
                'untry":"USA"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","i' .
                'dentity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":"8527","dob' .
                '_year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault' .
                '_api_id":"previousaccountvault123456","previous_token_api_id":"previousaccountv' .
                'ault123456","previous_account_vault_id":"11e95f8ec39de8fbdb0a4f1a","previous_to' .
                'ken_id":"11e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","account_number":"545454545454545","terms_agree":true,"terms_agree_ip"' .
                ':"192.168.0.10","title":"Test CC Account","token_import_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","secure_directory_server_transaction_id":"d65e93c3-35ab-41ba-b307-767bf' .
                'c19eae","secure_protocol_version":2,"secure_auth_data":"vVwL7UNHCf8W8M2LAfvRChN' .
                'HN7c%3D","secure_collection_indicator":null,"three_ds_server_trans_id":"d65e93c' .
                '3-35ab-41ba-b307-767bfc19eae","acs_transaction_id":"13c701a3-5a88-4c45-89e9-ef6' .
                '5e50a8bf9","_joi":{},"id":"11e95f8ec39de8fbdb0a4f1a","account_type":"checking",' .
                '"active":true,"cau_summary_status_id":1,"created_ts":1422040992,"e_serial_numbe' .
                'r":"1234567890","e_track_data":null,"e_format":null,"e_keyed_data":null,"expiri' .
                'ng_in_months":null,"exp_date":"0722","first_six":"700953","has_recurring":false' .
                ',"last_four":"3657","modified_ts":1422040992,"payment_method":"cc","ticket":nul' .
                'l,"track_data":null,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","cau_last_upda' .
                'ted_ts":1422040992,"routing_number":"051904524"},"created_user":{"account_numbe' .
                'r":"5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phone' .
                '":"3339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fb' .
                'db0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"333' .
                '9998822","first_name":"John","last_name":"Smith","locale":"en-US","office_phone' .
                '":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"Am' .
                'erica/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_expo' .
                'rt_type":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8e' .
                'c39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w' .
                '2","user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","loc' .
                'ation_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invit' .
                'ation":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","count' .
                'ry":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"las' .
                't_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"create' .
                'd_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agr' .
                'ee_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_l' .
                'ogin":1422040992,"log_api_response_body_ts":1422040992},"signature":{"signature' .
                '":"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqN' .
                'RiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIXtaXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/' .
                'y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfek' .
                'p4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6' .
                'NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvD' .
                'sH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJz' .
                'jumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGB' .
                'rmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDG' .
                'rNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8Bsgsvz' .
                'XEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vb' .
                'v1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed' .
                '0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcY' .
                'BHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+EC0ah++pNrAAAAAElFTkSuQmCC","resource"' .
                ':"Transaction","resource_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbd' .
                'b0a4f1a","created_ts":1422040992,"modified_ts":1422040992},"payment_schedule":[' .
                '"2021-12-01"],"location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"modified_ts":1422040992,"account_number":"5454545454545454","address":{"cit' .
                'y":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default' .
                '_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email' .
                '_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"location-11' .
                '1111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","l' .
                'ocation_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Hea' .
                'dquarters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"Am' .
                'erica/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":tru' .
                'e,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","locat' .
                'ion_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"product_tran' .
                'saction":{"processor_version":"1_0_0","title":"My terminal","payment_method":"c' .
                'c","processor":"zgate","mcc":"1111","tax_surcharge_config":2,"partner":"standal' .
                'one","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{' .
                '},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allo' .
                'w_debit":true,"ach_allow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt' .
                '_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":true,"receipt_show_' .
                'contact_name":true,"display_avs":true,"card_type_visa":true,"card_type_mc":true' .
                ',"card_type_disc":true,"card_type_amex":true,"card_type_diners":true,"card_type' .
                '_jcb":true,"card_type_ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt_food_s' .
                'tamp":true,"invoice_location":true,"allow_partial_authorization":true,"allow_re' .
                'curring_partial_authorization":true,"auto_decline_cvv":true,"auto_decline_stree' .
                't":true,"auto_decline_zip":true,"split_payments_allow":true,"vt_show_custom_fie' .
                'lds":true,"receipt_show_custom_fields":true,"vt_override_sales_tax_allowed":tru' .
                'e,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_require_street":true,"au' .
                'to_decline_cavv":true,"current_batch":34,"dup_check_per_batch":null,"paylink_al' .
                'low":false,"quick_invoice_allow":false,"level3_allow":false,"payfac_enable":fal' .
                'se,"enable_3ds":false,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_paym' .
                'ent_page_allow":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_comm' .
                'erce":false,"level3_default":{"destination_country_code":"840","duty_amount":0,' .
                '"freight_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ1234' .
                '5","shipto_zip_code":"MI48335","tax_amount":0,"tax_exempt":"0","customer_vat_re' .
                'gistration":"12345678","merchant_vat_registration":"123456","order_date":"17100' .
                '6","summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat123' .
                '4","line_items":[{"alternate_tax_id":"1234","debit_credit":"C","description":"c' .
                'ool drink","discount_amount":10,"discount_rate":11,"product_code":"coke12345678' .
                '","quantity":5,"tax_amount":3,"tax_rate":0,"tax_type_applied":"22","tax_type_id' .
                '":"a1","unit_code":"gll","unit_cost":10,"commodity_code":"cc123456","other_tax_' .
                'amount":0}]},"cau_subscribe_type_id":0,"location_billing_account_id":"11eb88b87' .
                '3980c64a21e5fd2","product_billing_group_id":"nofees","account_number":"12345678' .
                '","run_avs_on_accountvault_create":false,"accountvault_expire_notification_emai' .
                'l_enable":false,"debit_allow_void":false,"quick_invoice_text_to_pay":false,"sms' .
                '_enable":false,"vt_show_currency":true,"receipt_show_currency":false,"allow_bli' .
                'nd_refund":false,"vt_show_company_name":false,"receipt_show_company_name":false' .
                ',"bank_funded_only":false,"require_cvv_on_keyed_cnp":true,"require_cvv_on_token' .
                'ized_cnp":true,"show_secondary_amount":false,"allow_secondary_amount":false,"sh' .
                'ow_google_pay":true,"show_apple_pay":true,"batch_risk_config":{},"currency_code' .
                '":840,"enable_ach_validation":false,"enable_ach_retry":false,"id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts":1422040992,"c' .
                'reated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a","product_transaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary' .
                '_amount_allowed":false,"fortis_id":"8149742","product_billing_group_code":"nofe' .
                'es","cau_subscribe_type_code":0},"next_run_date_min":"2021-12-01","next_run_dat' .
                'e_max":"2021-12-01","all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","titl' .
                'e":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modif' .
                'ied_ts":1422040992}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts' .
                '":1422040992,"action":"CREATE","model":"TransactionRequest","model_id":"11ec829' .
                '598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"' .
                'id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field' .
                '":"next_run_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f' .
                '1a","username":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}],' .
                '"forecast":{"id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"Recurring ID","crea' .
                'ted_ts":1422040992,"modified_ts":1422040992},"recurring_splits":[{"id":"11e95f8' .
                'ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbd' .
                'b0a4f1a"}]}}'
            )))
            ->assert();
    }

    public function testPlaceOnHoldRecurringPayment()
    {
        // Parameters for the API call
        $recurringId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->placeOnHoldRecurringPayment($recurringId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Recurring","data":{"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","tok' .
                'en_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e95f8ec39de8fbdb0a4f1a","acco' .
                'unt_vault_api_id":"token1234abcd","token_api_id":"token1234abcd","_joi":{"condi' .
                'tions":{}},"active":true,"description":"Description","end_date":"2021-12-01","i' .
                'nstallment_total_count":20,"interval":1,"interval_type":"d","location_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","notification_days":2,"payment_method":"cc","product_tran' .
                'saction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","recurring_api_id":"recurring1234abcd","start_date":"2021-12-01","status":"ac' .
                'tive","transaction_amount":300,"terms_agree":true,"terms_agree_ip":"192.168.0.1' .
                '0","recurring_c1":"recurring custom data 1","recurring_c2":"recurring custom da' .
                'ta 2","recurring_c3":"recurring custom data 3","send_to_proc_as_recur":true,"ta' .
                'gs":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}],"secon' .
                'dary_amount":100,"currency":"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_dat' .
                'e":"2021-12-01","created_ts":1422040992,"modified_ts":1422040992,"recurring_typ' .
                'e_id":"i","installment_amount_total":99999999,"created_user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","log_emails":[{"subject":"Payment Receipt - 12skiestech","body":"Th' .
                'is email is being sent from a server.","source_address":"\\"12skiestech A7t3qi' .
                '\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3qi\\" <noreply@' .
                'zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c' .
                '4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sent":"Contact Em' .
                'ail","reason_model":"Transaction","reason_model_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec39de8fbdb0a4f1' .
                'a","created_ts":1422040992}],"contact":{"location_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","account_number":"54545433332","contact_api_id":"137","first_name":"John","la' .
                'st_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city":"' .
                'Novi","state":"Michigan","postal_code":"48375","country":"US"},"company_name":"' .
                'Fortis Payment Systems, LLC","header_message":"This is a sample message for you' .
                '","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999882' .
                '2","office_phone":"3339998822","office_phone_ext":"5","header_message_type":0,"' .
                'update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"so' .
                'mething","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","tok' .
                'en_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","creat' .
                'ed_ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id":"11e' .
                '95f8ec39de8fbdb0a4f1a"},"account_vault":{"account_holder_name":"John Smith","ac' .
                'count_vault_api_id":"accountvaultabcd","token_api_id":"tokenabcd","accountvault' .
                '_c1":"accountvault custom 1","accountvault_c2":"accountvault custom 2","account' .
                'vault_c3":"accountvault custom 3","token_c1":"token custom 1","token_c2":"token' .
                ' custom 2","token_c3":"token custom 3","ach_sec_code":"WEB","billing_address":{' .
                '"city":"Novi","state":"Michigan","postal_code":"48375","phone":"3339998822","co' .
                'untry":"USA"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","i' .
                'dentity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":"8527","dob' .
                '_year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault' .
                '_api_id":"previousaccountvault123456","previous_token_api_id":"previousaccountv' .
                'ault123456","previous_account_vault_id":"11e95f8ec39de8fbdb0a4f1a","previous_to' .
                'ken_id":"11e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","account_number":"545454545454545","terms_agree":true,"terms_agree_ip"' .
                ':"192.168.0.10","title":"Test CC Account","token_import_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","secure_directory_server_transaction_id":"d65e93c3-35ab-41ba-b307-767bf' .
                'c19eae","secure_protocol_version":2,"secure_auth_data":"vVwL7UNHCf8W8M2LAfvRChN' .
                'HN7c%3D","secure_collection_indicator":null,"three_ds_server_trans_id":"d65e93c' .
                '3-35ab-41ba-b307-767bfc19eae","acs_transaction_id":"13c701a3-5a88-4c45-89e9-ef6' .
                '5e50a8bf9","_joi":{},"id":"11e95f8ec39de8fbdb0a4f1a","account_type":"checking",' .
                '"active":true,"cau_summary_status_id":1,"created_ts":1422040992,"e_serial_numbe' .
                'r":"1234567890","e_track_data":null,"e_format":null,"e_keyed_data":null,"expiri' .
                'ng_in_months":null,"exp_date":"0722","first_six":"700953","has_recurring":false' .
                ',"last_four":"3657","modified_ts":1422040992,"payment_method":"cc","ticket":nul' .
                'l,"track_data":null,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","cau_last_upda' .
                'ted_ts":1422040992,"routing_number":"051904524"},"created_user":{"account_numbe' .
                'r":"5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phone' .
                '":"3339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fb' .
                'db0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"333' .
                '9998822","first_name":"John","last_name":"Smith","locale":"en-US","office_phone' .
                '":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"Am' .
                'erica/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_expo' .
                'rt_type":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8e' .
                'c39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w' .
                '2","user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","loc' .
                'ation_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invit' .
                'ation":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","count' .
                'ry":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"las' .
                't_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"create' .
                'd_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agr' .
                'ee_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_l' .
                'ogin":1422040992,"log_api_response_body_ts":1422040992},"signature":{"signature' .
                '":"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqN' .
                'RiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIXtaXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/' .
                'y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfek' .
                'p4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6' .
                'NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvD' .
                'sH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJz' .
                'jumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGB' .
                'rmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDG' .
                'rNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8Bsgsvz' .
                'XEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vb' .
                'v1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed' .
                '0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcY' .
                'BHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+EC0ah++pNrAAAAAElFTkSuQmCC","resource"' .
                ':"Transaction","resource_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbd' .
                'b0a4f1a","created_ts":1422040992,"modified_ts":1422040992},"payment_schedule":[' .
                '"2021-12-01"],"location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"modified_ts":1422040992,"account_number":"5454545454545454","address":{"cit' .
                'y":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default' .
                '_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email' .
                '_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"location-11' .
                '1111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","l' .
                'ocation_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Hea' .
                'dquarters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"Am' .
                'erica/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":tru' .
                'e,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","locat' .
                'ion_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"product_tran' .
                'saction":{"processor_version":"1_0_0","title":"My terminal","payment_method":"c' .
                'c","processor":"zgate","mcc":"1111","tax_surcharge_config":2,"partner":"standal' .
                'one","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{' .
                '},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allo' .
                'w_debit":true,"ach_allow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt' .
                '_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":true,"receipt_show_' .
                'contact_name":true,"display_avs":true,"card_type_visa":true,"card_type_mc":true' .
                ',"card_type_disc":true,"card_type_amex":true,"card_type_diners":true,"card_type' .
                '_jcb":true,"card_type_ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt_food_s' .
                'tamp":true,"invoice_location":true,"allow_partial_authorization":true,"allow_re' .
                'curring_partial_authorization":true,"auto_decline_cvv":true,"auto_decline_stree' .
                't":true,"auto_decline_zip":true,"split_payments_allow":true,"vt_show_custom_fie' .
                'lds":true,"receipt_show_custom_fields":true,"vt_override_sales_tax_allowed":tru' .
                'e,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_require_street":true,"au' .
                'to_decline_cavv":true,"current_batch":34,"dup_check_per_batch":null,"paylink_al' .
                'low":false,"quick_invoice_allow":false,"level3_allow":false,"payfac_enable":fal' .
                'se,"enable_3ds":false,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_paym' .
                'ent_page_allow":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_comm' .
                'erce":false,"level3_default":{"destination_country_code":"840","duty_amount":0,' .
                '"freight_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ1234' .
                '5","shipto_zip_code":"MI48335","tax_amount":0,"tax_exempt":"0","customer_vat_re' .
                'gistration":"12345678","merchant_vat_registration":"123456","order_date":"17100' .
                '6","summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat123' .
                '4","line_items":[{"alternate_tax_id":"1234","debit_credit":"C","description":"c' .
                'ool drink","discount_amount":10,"discount_rate":11,"product_code":"coke12345678' .
                '","quantity":5,"tax_amount":3,"tax_rate":0,"tax_type_applied":"22","tax_type_id' .
                '":"a1","unit_code":"gll","unit_cost":10,"commodity_code":"cc123456","other_tax_' .
                'amount":0}]},"cau_subscribe_type_id":0,"location_billing_account_id":"11eb88b87' .
                '3980c64a21e5fd2","product_billing_group_id":"nofees","account_number":"12345678' .
                '","run_avs_on_accountvault_create":false,"accountvault_expire_notification_emai' .
                'l_enable":false,"debit_allow_void":false,"quick_invoice_text_to_pay":false,"sms' .
                '_enable":false,"vt_show_currency":true,"receipt_show_currency":false,"allow_bli' .
                'nd_refund":false,"vt_show_company_name":false,"receipt_show_company_name":false' .
                ',"bank_funded_only":false,"require_cvv_on_keyed_cnp":true,"require_cvv_on_token' .
                'ized_cnp":true,"show_secondary_amount":false,"allow_secondary_amount":false,"sh' .
                'ow_google_pay":true,"show_apple_pay":true,"batch_risk_config":{},"currency_code' .
                '":840,"enable_ach_validation":false,"enable_ach_retry":false,"id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts":1422040992,"c' .
                'reated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a","product_transaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary' .
                '_amount_allowed":false,"fortis_id":"8149742","product_billing_group_code":"nofe' .
                'es","cau_subscribe_type_code":0},"next_run_date_min":"2021-12-01","next_run_dat' .
                'e_max":"2021-12-01","all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","titl' .
                'e":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modif' .
                'ied_ts":1422040992}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts' .
                '":1422040992,"action":"CREATE","model":"TransactionRequest","model_id":"11ec829' .
                '598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"' .
                'id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field' .
                '":"next_run_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f' .
                '1a","username":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}],' .
                '"forecast":{"id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"Recurring ID","crea' .
                'ted_ts":1422040992,"modified_ts":1422040992},"recurring_splits":[{"id":"11e95f8' .
                'ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbd' .
                'b0a4f1a"}]}}'
            )))
            ->assert();
    }
}
