<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\TransactionACHRetriesController;
use FortisAPILib\Exceptions;

class TransactionACHRetriesControllerTest extends BaseTestController
{
    /**
     * @var TransactionACHRetriesController TransactionACHRetriesController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getTransactionACHRetriesController();
    }

    public function testListAllTransactionACHRetriesRelated()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllTransactionACHRetriesRelated(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"TransactionAchRetrysCollection","list":[{"rejected_transaction_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","retry_transaction_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","return_fee_transaction_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","rejec' .
                'ted_transaction":{"additional_amounts":[{"type":"cashback","amount":10,"account' .
                '_type":"credit","currency":840}],"billing_address":{"city":"Novi","state":"Mich' .
                'igan","postal_code":"48375","phone":"3339998822","country":"USA"},"checkin_date' .
                '":"2021-12-01","checkout_date":"2021-12-01","clerk_number":"AE1234","contact_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","custom_data":{},"customer_id":"customerid","descr' .
                'iption":"some description","identity_verification":{"dl_state":"MI","dl_number"' .
                ':"1235567","dob_year":"1980"},"iias_ind":1,"image_front":"U29tZVN0cmluZ09idmlvd' .
                'XNseU5vdEJhc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2' .
                'NEVuY29kZWQ=","installment":true,"installment_number":1,"installment_count":1,"' .
                'location_api_id":"location-api-id-florida-2","location_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","advance_deposit":fa' .
                'lse,"no_show":false,"notification_email_address":"johnsmith@smiths.com","order_' .
                'number":"433659378839","po_number":"555555553123","quick_invoice_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","recurring":false,"recurring_number":1,"room_num":"303","room_' .
                'rate":95,"save_account":false,"save_account_title":"John Account","subtotal_amo' .
                'unt":599,"surcharge_amount":100,"tags":["Walk-in Customer"],"tax":0,"tip_amount' .
                '":0,"transaction_amount":0,"secondary_amount":0,"transaction_api_id":"transacti' .
                'on-payment-abcd123","transaction_c1":"custom-data-1","transaction_c2":"custom-d' .
                'ata-2","transaction_c3":"custom-data-3","bank_funded_only_override":false,"allo' .
                'w_partial_authorization_override":false,"auto_decline_cvv_override":false,"auto' .
                '_decline_street_override":false,"auto_decline_zip_override":false,"ebt_type":"f' .
                'ood_stamp","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts' .
                '":1422040992,"terminal_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_name":"sm' .
                'ith","account_type":"checking","token_id":"11e95f8ec39de8fbdb0a4f1a","ach_ident' .
                'ifier":"P","ach_sec_code":"C21","auth_amount":1,"auth_code":"BR349K","avs":"BAD' .
                '","avs_enhanced":"N","cardholder_present":true,"card_present":true,"check_numbe' .
                'r":"8520748520963","customer_ip":"192.168.0.10","cvv_response":"N","entry_mode_' .
                'id":"C","emv_receipt_data":{"AID":"a0000000042203","APPLAB":"US Maestro","APPN"' .
                ':"US Maestro","CVM":"Pin Verified","TSI":"e800","TVR":"0800008000"},"first_six"' .
                ':"545454","last_four":"5454","payment_method":"cc","terminal_serial_number":"12' .
                '34567890","transaction_settlement_status":null,"charge_back_date":"2021-12-01",' .
                '"is_recurring":true,"notification_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XY' .
                'G90R5D3E","reason_code_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f1a","sett' .
                'le_date":"2021-12-01","status_code":101,"transaction_batch_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","verbiage":"APPROVED","void_date":"2021-12-01","batch":"2","terms_ag' .
                'ree":true,"response_message":null,"return_date":"2021-12-01","trx_source_id":8,' .
                '"routing_number":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8fb' .
                'db0a4f1a","is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'modified_user_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","is_' .
                'token":true,"installment_total":1,"installment_counter":1,"account_vault_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"},"' .
                'retry_transaction":{"additional_amounts":[{"type":"cashback","amount":10,"accou' .
                'nt_type":"credit","currency":840}],"billing_address":{"city":"Novi","state":"Mi' .
                'chigan","postal_code":"48375","phone":"3339998822","country":"USA"},"checkin_da' .
                'te":"2021-12-01","checkout_date":"2021-12-01","clerk_number":"AE1234","contact_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","custom_data":{},"customer_id":"customerid","des' .
                'cription":"some description","identity_verification":{"dl_state":"MI","dl_numbe' .
                'r":"1235567","dob_year":"1980"},"iias_ind":1,"image_front":"U29tZVN0cmluZ09idml' .
                'vdXNseU5vdEJhc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2' .
                'U2NEVuY29kZWQ=","installment":true,"installment_number":1,"installment_count":1' .
                ',"location_api_id":"location-api-id-florida-2","location_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","advance_deposit":' .
                'false,"no_show":false,"notification_email_address":"johnsmith@smiths.com","orde' .
                'r_number":"433659378839","po_number":"555555553123","quick_invoice_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","recurring":false,"recurring_number":1,"room_num":"303","roo' .
                'm_rate":95,"save_account":false,"save_account_title":"John Account","subtotal_a' .
                'mount":599,"surcharge_amount":100,"tags":["Walk-in Customer"],"tax":0,"tip_amou' .
                'nt":0,"transaction_amount":0,"secondary_amount":0,"transaction_api_id":"transac' .
                'tion-payment-abcd123","transaction_c1":"custom-data-1","transaction_c2":"custom' .
                '-data-2","transaction_c3":"custom-data-3","bank_funded_only_override":false,"al' .
                'low_partial_authorization_override":false,"auto_decline_cvv_override":false,"au' .
                'to_decline_street_override":false,"auto_decline_zip_override":false,"ebt_type":' .
                '"food_stamp","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_' .
                'ts":1422040992,"terminal_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_name":"' .
                'smith","account_type":"checking","token_id":"11e95f8ec39de8fbdb0a4f1a","ach_ide' .
                'ntifier":"P","ach_sec_code":"C21","auth_amount":1,"auth_code":"BR349K","avs":"B' .
                'AD","avs_enhanced":"N","cardholder_present":true,"card_present":true,"check_num' .
                'ber":"8520748520963","customer_ip":"192.168.0.10","cvv_response":"N","entry_mod' .
                'e_id":"C","emv_receipt_data":{"AID":"a0000000042203","APPLAB":"US Maestro","APP' .
                'N":"US Maestro","CVM":"Pin Verified","TSI":"e800","TVR":"0800008000"},"first_si' .
                'x":"545454","last_four":"5454","payment_method":"cc","terminal_serial_number":"' .
                '1234567890","transaction_settlement_status":null,"charge_back_date":"2021-12-01' .
                '","is_recurring":true,"notification_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9' .
                'XYG90R5D3E","reason_code_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f1a","se' .
                'ttle_date":"2021-12-01","status_code":101,"transaction_batch_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","verbiage":"APPROVED","void_date":"2021-12-01","batch":"2","terms_' .
                'agree":true,"response_message":null,"return_date":"2021-12-01","trx_source_id":' .
                '8,"routing_number":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"modified_user_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","i' .
                's_token":true,"installment_total":1,"installment_counter":1,"account_vault_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"}' .
                ',"return_fee_transaction":{"additional_amounts":[{"type":"cashback","amount":10' .
                ',"account_type":"credit","currency":840}],"billing_address":{"city":"Novi","sta' .
                'te":"Michigan","postal_code":"48375","phone":"3339998822","country":"USA"},"che' .
                'ckin_date":"2021-12-01","checkout_date":"2021-12-01","clerk_number":"AE1234","c' .
                'ontact_id":"11e95f8ec39de8fbdb0a4f1a","custom_data":{},"customer_id":"customeri' .
                'd","description":"some description","identity_verification":{"dl_state":"MI","d' .
                'l_number":"1235567","dob_year":"1980"},"iias_ind":1,"image_front":"U29tZVN0cmlu' .
                'Z09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5' .
                'vdEJhc2U2NEVuY29kZWQ=","installment":true,"installment_number":1,"installment_c' .
                'ount":1,"location_api_id":"location-api-id-florida-2","location_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","advance_de' .
                'posit":false,"no_show":false,"notification_email_address":"johnsmith@smiths.com' .
                '","order_number":"433659378839","po_number":"555555553123","quick_invoice_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","recurring":false,"recurring_number":1,"room_num":"30' .
                '3","room_rate":95,"save_account":false,"save_account_title":"John Account","sub' .
                'total_amount":599,"surcharge_amount":100,"tags":["Walk-in Customer"],"tax":0,"t' .
                'ip_amount":0,"transaction_amount":0,"secondary_amount":0,"transaction_api_id":"' .
                'transaction-payment-abcd123","transaction_c1":"custom-data-1","transaction_c2":' .
                '"custom-data-2","transaction_c3":"custom-data-3","bank_funded_only_override":fa' .
                'lse,"allow_partial_authorization_override":false,"auto_decline_cvv_override":fa' .
                'lse,"auto_decline_street_override":false,"auto_decline_zip_override":false,"ebt' .
                '_type":"food_stamp","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"mo' .
                'dified_ts":1422040992,"terminal_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_' .
                'name":"smith","account_type":"checking","token_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'ach_identifier":"P","ach_sec_code":"C21","auth_amount":1,"auth_code":"BR349K","' .
                'avs":"BAD","avs_enhanced":"N","cardholder_present":true,"card_present":true,"ch' .
                'eck_number":"8520748520963","customer_ip":"192.168.0.10","cvv_response":"N","en' .
                'try_mode_id":"C","emv_receipt_data":{"AID":"a0000000042203","APPLAB":"US Maestr' .
                'o","APPN":"US Maestro","CVM":"Pin Verified","TSI":"e800","TVR":"0800008000"},"f' .
                'irst_six":"545454","last_four":"5454","payment_method":"cc","terminal_serial_nu' .
                'mber":"1234567890","transaction_settlement_status":null,"charge_back_date":"202' .
                '1-12-01","is_recurring":true,"notification_email_sent":true,"par":"Q1J4Z28RKA1E' .
                'BL470G9XYG90R5D3E","reason_code_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","settle_date":"2021-12-01","status_code":101,"transaction_batch_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","verbiage":"APPROVED","void_date":"2021-12-01","batch":"2",' .
                '"terms_agree":true,"response_message":null,"return_date":"2021-12-01","trx_sour' .
                'ce_id":8,"routing_number":"051904524","trx_source_code":8,"paylink_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12' .
                '-01","is_token":true,"installment_total":1,"installment_counter":1,"account_vau' .
                'lt_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0' .
                'a4f1a"},"created_user":{"account_number":"5454545454545454","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fortis Pay' .
                'ment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"202' .
                '1-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","ema' .
                'il_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last_name":' .
                '"Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","pr' .
                'imary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"ter' .
                'ms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":' .
                '"dashboard","page_size":2,"report_export_type":"csv","process_method":"virtual_' .
                'terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name' .
                '}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":' .
                '100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","sta' .
                'tus_code":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","st' .
                'ate":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":14220' .
                '40992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","te' .
                'rms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time"' .
                ':"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_t' .
                's":1422040992},"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422' .
                '040992,"action":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d' .
                '4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"nex' .
                't_run_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","u' .
                'sername":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}]}],"lin' .
                'ks":{"type":"Links","first":"/v1/endpoint?page[size]=10&page[number]=1","previo' .
                'us":"/v1/endpoint?page[size]=10&page[number]=5","next":"/v1/endpoint?page[size]' .
                '=10&page[number]=7","last":"/v1/endpoint?page[size]=10&page[number]=42"},"pagin' .
                'ation":{"type":"Pagination","total_count":423,"page_count":42,"page_number":6,"' .
                'page_size":10},"sort":{"type":"Sorting","fields":[{"field":"last_name","order":' .
                '"asc"}]}}'
            )))
            ->assert();
    }

    public function testViewSingleTransactionACHRetryRecord()
    {
        // Parameters for the API call
        $transactionAchRetryId =
            '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleTransactionACHRetryRecord(
                $transactionAchRetryId,
                $expand,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"TransactionAchRetry","data":{"rejected_transaction_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","retry_transaction_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","return_fee_transaction_id":"11e95f8ec39de8fbdb0a4f1a","created' .
                '_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","rejected_transact' .
                'ion":{"additional_amounts":[{"type":"cashback","amount":10,"account_type":"cred' .
                'it","currency":840}],"billing_address":{"city":"Novi","state":"Michigan","posta' .
                'l_code":"48375","phone":"3339998822","country":"USA"},"checkin_date":"2021-12-0' .
                '1","checkout_date":"2021-12-01","clerk_number":"AE1234","contact_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","custom_data":{},"customer_id":"customerid","description":"som' .
                'e description","identity_verification":{"dl_state":"MI","dl_number":"1235567","' .
                'dob_year":"1980"},"iias_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc' .
                '2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=' .
                '","installment":true,"installment_number":1,"installment_count":1,"location_api' .
                '_id":"location-api-id-florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","prod' .
                'uct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show' .
                '":false,"notification_email_address":"johnsmith@smiths.com","order_number":"433' .
                '659378839","po_number":"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","recurring":false,"recurring_number":1,"room_num":"303","room_rate":95,"sa' .
                've_account":false,"save_account_title":"John Account","subtotal_amount":599,"su' .
                'rcharge_amount":100,"tags":["Walk-in Customer"],"tax":0,"tip_amount":0,"transac' .
                'tion_amount":0,"secondary_amount":0,"transaction_api_id":"transaction-payment-a' .
                'bcd123","transaction_c1":"custom-data-1","transaction_c2":"custom-data-2","tran' .
                'saction_c3":"custom-data-3","bank_funded_only_override":false,"allow_partial_au' .
                'thorization_override":false,"auto_decline_cvv_override":false,"auto_decline_str' .
                'eet_override":false,"auto_decline_zip_override":false,"ebt_type":"food_stamp","' .
                'id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992' .
                ',"terminal_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_name":"smith","accoun' .
                't_type":"checking","token_id":"11e95f8ec39de8fbdb0a4f1a","ach_identifier":"P","' .
                'ach_sec_code":"C21","auth_amount":1,"auth_code":"BR349K","avs":"BAD","avs_enhan' .
                'ced":"N","cardholder_present":true,"card_present":true,"check_number":"85207485' .
                '20963","customer_ip":"192.168.0.10","cvv_response":"N","entry_mode_id":"C","emv' .
                '_receipt_data":{"AID":"a0000000042203","APPLAB":"US Maestro","APPN":"US Maestro' .
                '","CVM":"Pin Verified","TSI":"e800","TVR":"0800008000"},"first_six":"545454","l' .
                'ast_four":"5454","payment_method":"cc","terminal_serial_number":"1234567890","t' .
                'ransaction_settlement_status":null,"charge_back_date":"2021-12-01","is_recurrin' .
                'g":true,"notification_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","r' .
                'eason_code_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f1a","settle_date":"20' .
                '21-12-01","status_code":101,"transaction_batch_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'verbiage":"APPROVED","void_date":"2021-12-01","batch":"2","terms_agree":true,"r' .
                'esponse_message":null,"return_date":"2021-12-01","trx_source_id":8,"routing_num' .
                'ber":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8fbdb0a4f1a","i' .
                's_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_use' .
                'r_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","is_token":true,' .
                '"installment_total":1,"installment_counter":1,"account_vault_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"},"retry_transa' .
                'ction":{"additional_amounts":[{"type":"cashback","amount":10,"account_type":"cr' .
                'edit","currency":840}],"billing_address":{"city":"Novi","state":"Michigan","pos' .
                'tal_code":"48375","phone":"3339998822","country":"USA"},"checkin_date":"2021-12' .
                '-01","checkout_date":"2021-12-01","clerk_number":"AE1234","contact_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","custom_data":{},"customer_id":"customerid","description":"s' .
                'ome description","identity_verification":{"dl_state":"MI","dl_number":"1235567"' .
                ',"dob_year":"1980"},"iias_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJ' .
                'hc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZW' .
                'Q=","installment":true,"installment_number":1,"installment_count":1,"location_a' .
                'pi_id":"location-api-id-florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","pr' .
                'oduct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_sh' .
                'ow":false,"notification_email_address":"johnsmith@smiths.com","order_number":"4' .
                '33659378839","po_number":"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","recurring":false,"recurring_number":1,"room_num":"303","room_rate":95,"' .
                'save_account":false,"save_account_title":"John Account","subtotal_amount":599,"' .
                'surcharge_amount":100,"tags":["Walk-in Customer"],"tax":0,"tip_amount":0,"trans' .
                'action_amount":0,"secondary_amount":0,"transaction_api_id":"transaction-payment' .
                '-abcd123","transaction_c1":"custom-data-1","transaction_c2":"custom-data-2","tr' .
                'ansaction_c3":"custom-data-3","bank_funded_only_override":false,"allow_partial_' .
                'authorization_override":false,"auto_decline_cvv_override":false,"auto_decline_s' .
                'treet_override":false,"auto_decline_zip_override":false,"ebt_type":"food_stamp"' .
                ',"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":14220409' .
                '92,"terminal_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_name":"smith","acco' .
                'unt_type":"checking","token_id":"11e95f8ec39de8fbdb0a4f1a","ach_identifier":"P"' .
                ',"ach_sec_code":"C21","auth_amount":1,"auth_code":"BR349K","avs":"BAD","avs_enh' .
                'anced":"N","cardholder_present":true,"card_present":true,"check_number":"852074' .
                '8520963","customer_ip":"192.168.0.10","cvv_response":"N","entry_mode_id":"C","e' .
                'mv_receipt_data":{"AID":"a0000000042203","APPLAB":"US Maestro","APPN":"US Maest' .
                'ro","CVM":"Pin Verified","TSI":"e800","TVR":"0800008000"},"first_six":"545454",' .
                '"last_four":"5454","payment_method":"cc","terminal_serial_number":"1234567890",' .
                '"transaction_settlement_status":null,"charge_back_date":"2021-12-01","is_recurr' .
                'ing":true,"notification_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E",' .
                '"reason_code_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f1a","settle_date":"' .
                '2021-12-01","status_code":101,"transaction_batch_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"verbiage":"APPROVED","void_date":"2021-12-01","batch":"2","terms_agree":true,' .
                '"response_message":null,"return_date":"2021-12-01","trx_source_id":8,"routing_n' .
                'umber":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_u' .
                'ser_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","is_token":tru' .
                'e,"installment_total":1,"installment_counter":1,"account_vault_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"},"return_fee' .
                '_transaction":{"additional_amounts":[{"type":"cashback","amount":10,"account_ty' .
                'pe":"credit","currency":840}],"billing_address":{"city":"Novi","state":"Michiga' .
                'n","postal_code":"48375","phone":"3339998822","country":"USA"},"checkin_date":"' .
                '2021-12-01","checkout_date":"2021-12-01","clerk_number":"AE1234","contact_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","custom_data":{},"customer_id":"customerid","descript' .
                'ion":"some description","identity_verification":{"dl_state":"MI","dl_number":"1' .
                '235567","dob_year":"1980"},"iias_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNs' .
                'eU5vdEJhc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEV' .
                'uY29kZWQ=","installment":true,"installment_number":1,"installment_count":1,"loc' .
                'ation_api_id":"location-api-id-florida-2","location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","advance_deposit":false' .
                ',"no_show":false,"notification_email_address":"johnsmith@smiths.com","order_num' .
                'ber":"433659378839","po_number":"555555553123","quick_invoice_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","recurring":false,"recurring_number":1,"room_num":"303","room_rat' .
                'e":95,"save_account":false,"save_account_title":"John Account","subtotal_amount' .
                '":599,"surcharge_amount":100,"tags":["Walk-in Customer"],"tax":0,"tip_amount":0' .
                ',"transaction_amount":0,"secondary_amount":0,"transaction_api_id":"transaction-' .
                'payment-abcd123","transaction_c1":"custom-data-1","transaction_c2":"custom-data' .
                '-2","transaction_c3":"custom-data-3","bank_funded_only_override":false,"allow_p' .
                'artial_authorization_override":false,"auto_decline_cvv_override":false,"auto_de' .
                'cline_street_override":false,"auto_decline_zip_override":false,"ebt_type":"food' .
                '_stamp","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1' .
                '422040992,"terminal_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_name":"smith' .
                '","account_type":"checking","token_id":"11e95f8ec39de8fbdb0a4f1a","ach_identifi' .
                'er":"P","ach_sec_code":"C21","auth_amount":1,"auth_code":"BR349K","avs":"BAD","' .
                'avs_enhanced":"N","cardholder_present":true,"card_present":true,"check_number":' .
                '"8520748520963","customer_ip":"192.168.0.10","cvv_response":"N","entry_mode_id"' .
                ':"C","emv_receipt_data":{"AID":"a0000000042203","APPLAB":"US Maestro","APPN":"U' .
                'S Maestro","CVM":"Pin Verified","TSI":"e800","TVR":"0800008000"},"first_six":"5' .
                '45454","last_four":"5454","payment_method":"cc","terminal_serial_number":"12345' .
                '67890","transaction_settlement_status":null,"charge_back_date":"2021-12-01","is' .
                '_recurring":true,"notification_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XYG90' .
                'R5D3E","reason_code_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f1a","settle_' .
                'date":"2021-12-01","status_code":101,"transaction_batch_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","verbiage":"APPROVED","void_date":"2021-12-01","batch":"2","terms_agree' .
                '":true,"response_message":null,"return_date":"2021-12-01","trx_source_id":8,"ro' .
                'uting_number":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","mod' .
                'ified_user_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","is_tok' .
                'en":true,"installment_total":1,"installment_counter":1,"account_vault_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"},"cre' .
                'ated_user":{"account_number":"5454545454545454","branding_domain_url":"{brandin' .
                'g_domain_url}","cell_phone":"3339998822","company_name":"Fortis Payment Systems' .
                ', LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","do' .
                'main_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_recei' .
                'pt":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith","loc' .
                'ale":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_locati' .
                'on_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_condition' .
                '_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard",' .
                '"page_size":2,"report_export_type":"csv","process_method":"virtual_terminal","d' .
                'efault_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api' .
                '_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"passwor' .
                'd":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,' .
                '"api_only":false,"is_invitation":false,"address":{"city":"Novi","state":"MI","p' .
                'ostal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":tr' .
                'ue,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modif' .
                'ied_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted' .
                '_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11' .
                'T10:38:26-0700","current_login":1422040992,"log_api_response_body_ts":142204099' .
                '2},"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"acti' .
                'on":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4"' .
                ',"user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de' .
                '8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","o' .
                'ld_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"em' .
                'ail@domain.com","first_name":"Bob","last_name":"Fairview"}}]}}'
            )))
            ->assert();
    }
}
