<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\TransactionsReadController;
use FortisAPILib\Exceptions;

class TransactionsReadControllerTest extends BaseTestController
{
    /**
     * @var TransactionsReadController TransactionsReadController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getTransactionsReadController();
    }

    public function testGetBINInfo()
    {
        // Parameters for the API call
        $transactionId = '11e95f8ec39de8fbdb0a4f1a';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->getBINInfo($transactionId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"TransactionBinInfo","data":{"issuer_bank_name":"Cartasi S.P.A.","coun' .
                'try_code":"US","detail_card_product":"V","detail_card_indicator":"X","fsa_indic' .
                'ator":"F","prepaid_indicator":"P","product_id":"G","regulator_indicator":"N","v' .
                'isa_product_sub_type":null,"visa_large_ticket_indicator":null,"account_fund_sou' .
                'rce":"C","card_class":"B","token_ind":null,"issuing_network":null}}'
            )))
            ->assert();
    }

    public function testGetTransaction()
    {
        // Parameters for the API call
        $transactionId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->getTransaction($transactionId, $expand, $fields);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Transaction","data":{"additional_amounts":[{"type":"cashback","amount' .
                '":10,"account_type":"credit","currency":840}],"billing_address":{"city":"Novi",' .
                '"state":"Michigan","postal_code":"48375","phone":"3339998822","country":"USA"},' .
                '"checkin_date":"2021-12-01","checkout_date":"2021-12-01","clerk_number":"AE1234' .
                '","contact_id":"11e95f8ec39de8fbdb0a4f1a","custom_data":{},"customer_id":"custo' .
                'merid","description":"some description","iias_ind":1,"image_front":"U29tZVN0cml' .
                'uZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU' .
                '5vdEJhc2U2NEVuY29kZWQ=","installment":true,"installment_number":1,"installment_' .
                'count":1,"location_api_id":"location-api-id-florida-2","location_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","advance_d' .
                'eposit":false,"no_show":false,"notification_email_address":"johnsmith@smiths.co' .
                'm","order_number":"433659378839","po_number":"555555553123","quick_invoice_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","recurring":{"account_vault_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","token_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","account_vault_api_id":"token1234abcd","token_api_id":"token1234abcd","_j' .
                'oi":{"conditions":{}},"active":true,"description":"Description","end_date":"202' .
                '1-12-01","installment_total_count":20,"interval":1,"interval_type":"d","locatio' .
                'n_id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"payment_method":"cc","p' .
                'roduct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","recurring_api_id":"recurring1234abcd","start_date":"2021-12-01","' .
                'status":"active","transaction_amount":300,"terms_agree":true,"terms_agree_ip":"' .
                '192.168.0.10","recurring_c1":"recurring custom data 1","recurring_c2":"recurrin' .
                'g custom data 2","recurring_c3":"recurring custom data 3","send_to_proc_as_recu' .
                'r":true,"tags":["Walk-in Customer"],"secondary_amount":100,"currency":"USD","id' .
                '":"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","created_ts":14220409' .
                '92,"modified_ts":1422040992,"recurring_type_id":"i","installment_amount_total":' .
                '99999999,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"recurring_number":1,"ro' .
                'om_num":"303","room_rate":95,"save_account":false,"save_account_title":"John Ac' .
                'count","subtotal_amount":599,"surcharge_amount":100,"tags":[{"location_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","title":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","c' .
                'reated_ts":1422040992,"modified_ts":1422040992}],"tax":0,"tip_amount":0,"transa' .
                'ction_amount":0,"secondary_amount":0,"transaction_api_id":"transaction-payment-' .
                'abcd123","transaction_c1":"custom-data-1","transaction_c2":"custom-data-2","tra' .
                'nsaction_c3":"custom-data-3","bank_funded_only_override":false,"allow_partial_a' .
                'uthorization_override":false,"auto_decline_cvv_override":false,"auto_decline_st' .
                'reet_override":false,"auto_decline_zip_override":false,"ebt_type":"food_stamp",' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204099' .
                '2,"terminal_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_name":"smith","accou' .
                'nt_type":"checking","token_id":"11e95f8ec39de8fbdb0a4f1a","ach_identifier":"P",' .
                '"ach_sec_code":"C21","auth_amount":1,"auth_code":"BR349K","avs":"BAD","avs_enha' .
                'nced":"N","cardholder_present":true,"card_present":true,"check_number":"8520748' .
                '520963","customer_ip":"192.168.0.10","cvv_response":"N","entry_mode_id":"C","em' .
                'v_receipt_data":{"AID":"a0000000042203","APPLAB":"US Maestro","APPN":"US Maestr' .
                'o","CVM":"Pin Verified","TSI":"e800","TVR":"0800008000"},"first_six":"545454","' .
                'last_four":"5454","payment_method":"cc","terminal_serial_number":"1234567890","' .
                'transaction_settlement_status":null,"charge_back_date":"2021-12-01","is_recurri' .
                'ng":true,"notification_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","' .
                'reason_code_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f1a","settle_date":"2' .
                '021-12-01","status_code":101,"transaction_batch_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"verbiage":"APPROVED","void_date":"2021-12-01","batch":"2","terms_agree":true,"' .
                'response_message":null,"return_date":"2021-12-01","trx_source_id":8,"routing_nu' .
                'mber":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","is_token":true' .
                ',"installment_total":1,"installment_counter":1,"account_vault_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a","account_vaul' .
                't":{"account_holder_name":"John Smith","account_vault_api_id":"accountvaultabcd' .
                '","token_api_id":"tokenabcd","accountvault_c1":"accountvault custom 1","account' .
                'vault_c2":"accountvault custom 2","accountvault_c3":"accountvault custom 3","to' .
                'ken_c1":"token custom 1","token_c2":"token custom 2","token_c3":"token custom 3' .
                '","ach_sec_code":"WEB","billing_address":{"city":"Novi","state":"Michigan","pos' .
                'tal_code":"48375","phone":"3339998822","country":"USA"},"contact_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","customer_id":"123456","identity_verification":{"dl_state":"MI' .
                '","dl_number":"1235567","ssn4":"8527","dob_year":"1980"},"location_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","previous_account_vault_api_id":"previousaccountvault123456"' .
                ',"previous_token_api_id":"previousaccountvault123456","previous_account_vault_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","previous_token_id":"11e95f8ec39de8fbdb0a4f1a","p' .
                'revious_transaction_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"5454545454' .
                '54545","terms_agree":true,"terms_agree_ip":"192.168.0.10","title":"Test CC Acco' .
                'unt","token_import_id":"11e95f8ec39de8fbdb0a4f1a","secure_directory_server_tran' .
                'saction_id":"d65e93c3-35ab-41ba-b307-767bfc19eae","secure_protocol_version":2,"' .
                'secure_auth_data":"vVwL7UNHCf8W8M2LAfvRChNHN7c%3D","secure_collection_indicator' .
                '":null,"three_ds_server_trans_id":"d65e93c3-35ab-41ba-b307-767bfc19eae","acs_tr' .
                'ansaction_id":"13c701a3-5a88-4c45-89e9-ef65e50a8bf9","_joi":{},"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","account_type":"checking","active":true,"cau_summary_status_id"' .
                ':1,"created_ts":1422040992,"e_serial_number":"1234567890","e_track_data":null,"' .
                'e_format":null,"e_keyed_data":null,"expiring_in_months":null,"exp_date":"0722",' .
                '"first_six":"700953","has_recurring":false,"last_four":"3657","modified_ts":142' .
                '2040992,"payment_method":"cc","ticket":null,"track_data":null,"created_user_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","cau_last_updated_ts":1422040992,"routing_number":"' .
                '051904524"},"quick_invoice":{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"' .
                'My terminal","cc_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","ach_produc' .
                't_transaction_id":"11e95f8ec39de8fbdb0a4f1a","due_date":"2021-12-01","item_list' .
                '":[{"name":"Bread","amount":2015}],"allow_overpayment":true,"bank_funded_only_o' .
                'verride":true,"email":"email@domain.com","contact_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","contact_api_id":"contact12345","quick_invoice_api_id":"quickinvoice12345","c' .
                'ustomer_id":"11e95f8ec39de8fbdb0a4f1a","expire_date":"2021-12-01","allow_partia' .
                'l_pay":true,"attach_files_to_email":true,"send_email":true,"invoice_number":"in' .
                'voice12345","item_header":"Quick invoice header sample","item_footer":"Thank yo' .
                'u","amount_due":245.36,"notification_email":"email@domain.com","status_id":1,"s' .
                'tatus_code":1,"note":"some note","notification_days_before_due_date":3,"notific' .
                'ation_days_after_due_date":7,"notification_on_due_date":true,"send_text_to_pay"' .
                ':true,"files":[{}],"remaining_balance":245.36,"single_payment_min_amount":500,"' .
                'single_payment_max_amount":500000,"cell_phone":"3339998822","tags":["Walk-in Cu' .
                'stomer"],"quick_invoice_c1":"custom-data-1","quick_invoice_c2":"custom-data-2",' .
                '"quick_invoice_c3":"custom-data-3","auto_reopen":true,"id":"11e95f8ec39de8fbdb0' .
                'a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","active":tr' .
                'ue,"payment_status_id":1,"is_active":true},"log_emails":[{"subject":"Payment Re' .
                'ceipt - 12skiestech","body":"This email is being sent from a server.","source_a' .
                'ddress":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"1' .
                '2skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-' .
                'e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","reason_sent":"Contact Email","reason_model":"Transaction","reason_model_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>"' .
                ',"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"is_voidable":true,"' .
                'is_reversible":true,"is_refundable":true,"is_completable":true,"is_settled":tru' .
                'e,"created_user":{"account_number":"5454545454545454","branding_domain_url":"{b' .
                'randing_domain_url}","cell_phone":"3339998822","company_name":"Fortis Payment S' .
                'ystems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-0' .
                '1","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx' .
                '_receipt":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith' .
                '","locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_' .
                'location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_con' .
                'dition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashb' .
                'oard","page_size":2,"report_export_type":"csv","process_method":"virtual_termin' .
                'al","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","us' .
                'er_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"p' .
                'assword":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_co' .
                'de":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","state":"' .
                'MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","stat' .
                'us":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,' .
                '"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_ac' .
                'cepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019' .
                '-03-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_ts":142' .
                '2040992},"location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"m' .
                'odified_ts":1422040992,"account_number":"5454545454545454","address":{"city":"N' .
                'ovi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach"' .
                ':"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_repl' .
                'y_to":"email@domain.com","fax":"3339998822","location_api_id":"location-111111"' .
                ',"location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","locati' .
                'on_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Headquar' .
                'ters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"America' .
                '/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"sh' .
                'ow_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_t' .
                'ype":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"contact":{"locati' .
                'on_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_i' .
                'd":"137","first_name":"John","last_name":"Smith","cell_phone":"3339998822","bal' .
                'ance":245.36,"address":{"city":"Novi","state":"Michigan","postal_code":"48375",' .
                '"country":"US"},"company_name":"Fortis Payment Systems, LLC","header_message":"' .
                'This is a sample message for you","date_of_birth":"2021-12-01","email_trx_recei' .
                'pt":true,"home_phone":"3339998822","office_phone":"3339998822","office_phone_ex' .
                't":"5","header_message_type":0,"update_if_exists":1,"contact_c1":"any","contact' .
                '_c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"' .
                '11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"act' .
                'ive":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"changelogs":[{"id":"11' .
                'e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"Tran' .
                'sactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"' .
                'user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_nam' .
                'e":"Bob","last_name":"Fairview"}}],"product_transaction":{"processor_version":"' .
                '1_0_0","title":"My terminal","payment_method":"cc","processor":"zgate","mcc":"1' .
                '111","tax_surcharge_config":2,"partner":"standalone","location_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","surcharge":{},"processor_data":{},"vt_clerk_number":true,"vt_bi' .
                'lling_phone":true,"vt_enable_tip":true,"ach_allow_debit":true,"ach_allow_credit' .
                '":true,"ach_allow_refund":true,"vt_cvv":true,"vt_street":true,"vt_zip":true,"vt' .
                '_order_num":true,"vt_enable":true,"receipt_show_contact_name":true,"display_avs' .
                '":true,"card_type_visa":true,"card_type_mc":true,"card_type_disc":true,"card_ty' .
                'pe_amex":true,"card_type_diners":true,"card_type_jcb":true,"card_type_ebt":true' .
                ',"allow_ebt_cash_benefit":true,"allow_ebt_food_stamp":true,"invoice_location":t' .
                'rue,"allow_partial_authorization":true,"allow_recurring_partial_authorization":' .
                'true,"auto_decline_cvv":true,"auto_decline_street":true,"auto_decline_zip":true' .
                ',"split_payments_allow":true,"vt_show_custom_fields":true,"receipt_show_custom_' .
                'fields":true,"vt_override_sales_tax_allowed":true,"vt_enable_sales_tax":true,"v' .
                't_require_zip":true,"vt_require_street":true,"auto_decline_cavv":true,"current_' .
                'batch":34,"dup_check_per_batch":null,"paylink_allow":false,"quick_invoice_allow' .
                '":false,"level3_allow":false,"payfac_enable":false,"enable_3ds":false,"sales_of' .
                'fice_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,"surcharg' .
                'e_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_commerce":false,"level3_default":{"' .
                'destination_country_code":"840","duty_amount":0,"freight_amount":0,"national_ta' .
                'x":2,"sales_tax":200,"shipfrom_zip_code":"AZ12345","shipto_zip_code":"MI48335",' .
                '"tax_amount":0,"tax_exempt":"0","customer_vat_registration":"12345678","merchan' .
                't_vat_registration":"123456","order_date":"171006","summary_commodity_code":"C1' .
                'K2","tax_rate":0,"unique_vat_ref_number":"vat1234","line_items":[{"alternate_ta' .
                'x_id":"1234","debit_credit":"C","description":"cool drink","discount_amount":10' .
                ',"discount_rate":11,"product_code":"coke12345678","quantity":5,"tax_amount":3,"' .
                'tax_rate":0,"tax_type_applied":"22","tax_type_id":"a1","unit_code":"gll","unit_' .
                'cost":10,"commodity_code":"cc123456","other_tax_amount":0}]},"cau_subscribe_typ' .
                'e_id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","product_billi' .
                'ng_group_id":"nofees","account_number":"12345678","run_avs_on_accountvault_crea' .
                'te":false,"accountvault_expire_notification_email_enable":false,"debit_allow_vo' .
                'id":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_show_currenc' .
                'y":true,"receipt_show_currency":false,"allow_blind_refund":false,"vt_show_compa' .
                'ny_name":false,"receipt_show_company_name":false,"bank_funded_only":false,"requ' .
                'ire_cvv_on_keyed_cnp":true,"require_cvv_on_tokenized_cnp":true,"show_secondary_' .
                'amount":false,"allow_secondary_amount":false,"show_google_pay":true,"show_apple' .
                '_pay":true,"batch_risk_config":{},"currency_code":840,"enable_ach_validation":f' .
                'alse,"enable_ach_retry":false,"id":"11e95f8ec39de8fbdb0a4f1a","active":true,"cr' .
                'eated_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_' .
                'api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary_amount_allowed":false,"fortis_' .
                'id":"8149742","product_billing_group_code":"nofees","cau_subscribe_type_code":0' .
                '},"all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","' .
                'id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992' .
                '}],"tagTransactions":[{"id":"11e95f8ec39de8fbdb0a4f1a","tag_id":"Tag ID","trans' .
                'action_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142' .
                '2040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f' .
                '8ec39de8fbdb0a4f1a"}],"declined_recurring_notification":{"id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"modified_ts":1422040992,"modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"paymen' .
                't_recurring_notification":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040' .
                '992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_ts":1422040992,"modi' .
                'fied_user_id":"11e95f8ec39de8fbdb0a4f1a"},"developer_company":{"title":"My term' .
                'inal","id":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"mo' .
                'dified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a"},"terminal":{"location_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","default_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","terminal_' .
                'application_id":"11e95f8ec39de8fbdb0a4f1a","terminal_cvm_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","terminal_manufacturer_code":"1","title":"My terminal","mac_address":"' .
                '3D:F2:C9:A6:B3:4F","local_ip_address":"192.168.0.10","port":10009,"serial_numbe' .
                'r":"1234567890","terminal_number":"973456789012367","terminal_timeouts":{"card_' .
                'entry_timeout":47,"device_terms_prompt_timeout":30,"overall_timeout":125,"pin_e' .
                'ntry_timeout":40,"signature_input_timeout":35,"signature_submit_timeout":38,"st' .
                'atus_display_time":12,"tip_cashback_timeout":25,"transaction_timeout":17},"tip_' .
                'percents":{"percent_1":0,"percent_2":2,"percent_3":99},"header_line_1":"line 1 ' .
                'sample","header_line_2":"line 2 sample","header_line_3":"line 3 sample","header' .
                '_line_4":"line 4 sample","header_line_5":"line 5 sample","trailer_line_1":"trai' .
                'ler 1 sample","trailer_line_2":"trailer 2 sample","trailer_line_3":"trailer 3 s' .
                'ample","trailer_line_4":"trailer 4 sample","trailer_line_5":"trailer 5 sample",' .
                '"default_checkin":"2021-12-01","default_checkout":"2021-12-01","default_room_ra' .
                'te":56,"default_room_number":"303","debit":false,"emv":false,"cashback_enable":' .
                'false,"print_enable":false,"sig_capture_enable":false,"is_provisioned":false,"t' .
                'ip_enable":false,"validated_decryption":false,"communication_type":"http","acti' .
                've":true,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":' .
                '1422040992,"last_registration_ts":1422040992,"created_user_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"hosted_payment_page"' .
                ':{"user_id":"11e95f8ec39de8fbdb0a4f1a","location_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"location_api_id":null,"product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","ti' .
                'tle":"Sample title","redirect_url_delay":15,"min_payment_amount":0,"max_payment' .
                '_amount":9999999999,"redirect_url_on_approve":null,"redirect_url_on_decline":nu' .
                'll,"field_configuration":{"css_mini":true,"stack":"vertical","header":{"setting' .
                's":{"enabled":true,"columns":1,"rows":1},"fields":[{"id":"transaction_amount","' .
                'label":"Header","field_type":"heading","position":["1"],"required":true,"readon' .
                'ly":true,"visible":true}]},"body":{"settings":{"enabled":true,"columns":1,"rows' .
                '":1},"fields":[{"id":"transaction_amount","label":"Header","field_type":"headin' .
                'g","position":["1"],"required":true,"readonly":true,"visible":true}]},"footer":' .
                '{"settings":{"enabled":true,"columns":1,"rows":1},"fields":[{"id":"transaction_' .
                'amount","label":"Header","field_type":"heading","position":["1"],"required":tru' .
                'e,"readonly":true,"visible":true}]}},"encryption_key":null,"stylesheet_url":nul' .
                'l,"parent_send_message":true,"hide_optional_fields":true,"id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"transa' .
                'ction_level3":{"id":"11e95f8ec39de8fbdb0a4f1a","transaction_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","level3_data":{"destination_country_code":"840","duty_amount":0,"fr' .
                'eight_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ1234","' .
                'shipto_zip_code":"FL1234","tax_amount":10,"tax_exempt":"0","customer_vat_regist' .
                'ration":"12345678","merchant_vat_registration":"123456","order_date":"171006","' .
                'summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat1234","' .
                'line_items":[{"description":"cool drink","commodity_code":"cc123456","discount_' .
                'amount":0,"other_tax_amount":0,"product_code":"fanta123456","quantity":12,"tax_' .
                'amount":4,"tax_rate":0,"unit_code":"gll","unit_cost":3,"alternate_tax_id":"1234' .
                '","debit_credit":"C","discount_rate":11,"tax_type_applied":"22","tax_type_id":"' .
                '11"}]}},"developer_company_id":"Sample Developer Company ID","transaction_histo' .
                'ries":[{"transaction_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4' .
                'f1a","status_id":101,"event_date_ts":1422040992,"location_id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992}],"surcharge_transac' .
                'tion":{"id":"11e95f8ec39de8fbdb0a4f1a","model_name":"Model Name","transaction_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","surcharge_fee":0,"surcharge_rate":0,"surcharge_a' .
                'mount":null,"surcharge_transaction_min":null,"surcharge_transaction_max":null,"' .
                'created":1422040992,"modified":1422040992,"created_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"surcharge":{"surcharge_' .
                'fee":10,"surcharge_rate":1,"product_transaction_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"apply_to_user_type_id":"11e95f8ec39de8fbdb0a4f1a","title":null,"surcharge_labe' .
                'l":null,"surcharge_transaction_product_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e' .
                '95f8ec39de8fbdb0a4f1a","created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_u' .
                'ser_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204' .
                '0992},"signature":{"signature":"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAA' .
                'CvklEQVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIXtaXw2H3/5' .
                's5MwZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6WCxURDTLs' .
                'qmngzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FNrCzLm5j68Q1F' .
                'x2o3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnqfeQ/bzHkgOIf' .
                '0VzHP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b4NLU3T9jVbTLcRnM' .
                'O620ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6aSr1UpFRPf7ffveu' .
                'q41TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYax7EmSXJ3DD2v624r' .
                'zUpoVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9' .
                'WqbFRPaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1wR371z1zP' .
                'nKlbDGuvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/l' .
                'Nsym+DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEc' .
                'YBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+EC0ah++pN' .
                'rAAAAAElFTkSuQmCC","resource":"Transaction","resource_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142' .
                '2040992},"reason_code":{"id":50,"title":"Sample Title"},"type":{"id":50,"title"' .
                ':"Sample Title"},"status":{"id":50,"title":"Sample Title"},"transaction_batch":' .
                '{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"product_transaction_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","processing_status_id":2,"batch_num":4,"is_open":' .
                '0,"settlement_file_name":"settement_file.txt","batch_close_ts":1531423693,"batc' .
                'h_close_detail":"BATCH_MISMATCH","total_sale_amount":2342,"total_sale_count":21' .
                ',"total_refund_amount":2342,"total_refund_count":18,"total_void_amount":2342,"t' .
                'otal_void_count":17,"total_blind_refund_amount":2342,"total_blind_refund_count"' .
                ':16},"transaction_splits":[{"transaction_id":"11e95f8ec39de8fbdb0a4f1a","contac' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","amount":10,"id":"11e95f8ec39de8fbdb0a4f1a","c' .
                'reated_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"postback_' .
                'logs":[{"id":"11e95f8ec39de8fbdb0a4f1a","postback_config_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","next_run_ts":1422040992,"cr' .
                'eated_ts":1422040992,"model_id":"11e95f8ec39de8fbdb0a4f1a"}],"currency_type":{"' .
                'id":50,"title":"Sample Title"},"transaction_references":[{"id":"11e95f8ec39de8f' .
                'bdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                '}],"rejected_transaction_ach_retries":[{"rejected_transaction_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","retry_transaction_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","return_fee_transaction_id":"11e95f8ec39de8fbdb0a4f1a","create' .
                'd_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"return_fee_tra' .
                'nsaction_ach_retry":{"rejected_transaction_id":"11e95f8ec39de8fbdb0a4f1a","id":' .
                '"11e95f8ec39de8fbdb0a4f1a","retry_transaction_id":"11e95f8ec39de8fbdb0a4f1a","r' .
                'eturn_fee_transaction_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"c' .
                'reated_user_id":"11e95f8ec39de8fbdb0a4f1a"},"retry_transaction_ach_retry":{"rej' .
                'ected_transaction_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a' .
                '","retry_transaction_id":"11e95f8ec39de8fbdb0a4f1a","return_fee_transaction_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8e' .
                'c39de8fbdb0a4f1a"},"saved_account":{"account_holder_name":"John Smith","account' .
                '_vault_api_id":"accountvaultabcd","token_api_id":"tokenabcd","accountvault_c1":' .
                '"accountvault custom 1","accountvault_c2":"accountvault custom 2","accountvault' .
                '_c3":"accountvault custom 3","token_c1":"token custom 1","token_c2":"token cust' .
                'om 2","token_c3":"token custom 3","ach_sec_code":"WEB","billing_address":{"city' .
                '":"Novi","state":"Michigan","postal_code":"48375","phone":"3339998822","country' .
                '":"USA"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","identi' .
                'ty_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":"8527","dob_year' .
                '":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault_api_' .
                'id":"previousaccountvault123456","previous_token_api_id":"previousaccountvault1' .
                '23456","previous_account_vault_id":"11e95f8ec39de8fbdb0a4f1a","previous_token_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","account_number":"545454545454545","terms_agree":true,"terms_agree_ip":"192' .
                '.168.0.10","title":"Test CC Account","token_import_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","secure_directory_server_transaction_id":"d65e93c3-35ab-41ba-b307-767bfc19ea' .
                'e","secure_protocol_version":2,"secure_auth_data":"vVwL7UNHCf8W8M2LAfvRChNHN7c%' .
                '3D","secure_collection_indicator":null,"three_ds_server_trans_id":"d65e93c3-35a' .
                'b-41ba-b307-767bfc19eae","acs_transaction_id":"13c701a3-5a88-4c45-89e9-ef65e50a' .
                '8bf9","_joi":{},"id":"11e95f8ec39de8fbdb0a4f1a","account_type":"checking","acti' .
                've":true,"cau_summary_status_id":1,"created_ts":1422040992,"e_serial_number":"1' .
                '234567890","e_track_data":null,"e_format":null,"e_keyed_data":null,"expiring_in' .
                '_months":null,"exp_date":"0722","first_six":"700953","has_recurring":false,"las' .
                't_four":"3657","modified_ts":1422040992,"payment_method":"cc","ticket":null,"tr' .
                'ack_data":null,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","cau_last_updated_t' .
                's":1422040992,"routing_number":"051904524"},"balances":[{"amount":1000}]}}'
            )))
            ->assert();
    }

    public function testListTransactions()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listTransactions(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"TransactionsCollection","list":[{"additional_amounts":[{"type":"cashb' .
                'ack","amount":10,"account_type":"credit","currency":840}],"billing_address":{"c' .
                'ity":"Novi","state":"Michigan","postal_code":"48375","phone":"3339998822","coun' .
                'try":"USA"},"checkin_date":"2021-12-01","checkout_date":"2021-12-01","clerk_num' .
                'ber":"AE1234","contact_id":"11e95f8ec39de8fbdb0a4f1a","custom_data":{},"custome' .
                'r_id":"customerid","description":"some description","iias_ind":1,"image_front":' .
                '"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ0' .
                '9idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","installment":true,"installment_number":1,"' .
                'installment_count":1,"location_api_id":"location-api-id-florida-2","location_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","advance_deposit":false,"no_show":false,"notification_email_address":"johnsmi' .
                'th@smiths.com","order_number":"433659378839","po_number":"555555553123","quick_' .
                'invoice_id":"11e95f8ec39de8fbdb0a4f1a","recurring":{"account_vault_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","token_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e95f8e' .
                'c39de8fbdb0a4f1a","account_vault_api_id":"token1234abcd","token_api_id":"token1' .
                '234abcd","_joi":{"conditions":{}},"active":true,"description":"Description","en' .
                'd_date":"2021-12-01","installment_total_count":20,"interval":1,"interval_type":' .
                '"d","location_id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"payment_met' .
                'hod":"cc","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","recurring_api_id":"recurring1234abcd","start_date":"2' .
                '021-12-01","status":"active","transaction_amount":300,"terms_agree":true,"terms' .
                '_agree_ip":"192.168.0.10","recurring_c1":"recurring custom data 1","recurring_c' .
                '2":"recurring custom data 2","recurring_c3":"recurring custom data 3","send_to_' .
                'proc_as_recur":true,"tags":["Walk-in Customer"],"secondary_amount":100,"currenc' .
                'y":"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","created_' .
                'ts":1422040992,"modified_ts":1422040992,"recurring_type_id":"i","installment_am' .
                'ount_total":99999999,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"recurring_n' .
                'umber":1,"room_num":"303","room_rate":95,"save_account":false,"save_account_tit' .
                'le":"John Account","subtotal_amount":599,"surcharge_amount":100,"tags":[{"locat' .
                'ion_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992}],"tax":0,"tip_amoun' .
                't":0,"transaction_amount":0,"secondary_amount":0,"transaction_api_id":"transact' .
                'ion-payment-abcd123","transaction_c1":"custom-data-1","transaction_c2":"custom-' .
                'data-2","transaction_c3":"custom-data-3","bank_funded_only_override":false,"all' .
                'ow_partial_authorization_override":false,"auto_decline_cvv_override":false,"aut' .
                'o_decline_street_override":false,"auto_decline_zip_override":false,"ebt_type":"' .
                'food_stamp","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_t' .
                's":1422040992,"terminal_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_name":"s' .
                'mith","account_type":"checking","token_id":"11e95f8ec39de8fbdb0a4f1a","ach_iden' .
                'tifier":"P","ach_sec_code":"C21","auth_amount":1,"auth_code":"BR349K","avs":"BA' .
                'D","avs_enhanced":"N","cardholder_present":true,"card_present":true,"check_numb' .
                'er":"8520748520963","customer_ip":"192.168.0.10","cvv_response":"N","entry_mode' .
                '_id":"C","emv_receipt_data":{"AID":"a0000000042203","APPLAB":"US Maestro","APPN' .
                '":"US Maestro","CVM":"Pin Verified","TSI":"e800","TVR":"0800008000"},"first_six' .
                '":"545454","last_four":"5454","payment_method":"cc","terminal_serial_number":"1' .
                '234567890","transaction_settlement_status":null,"charge_back_date":"2021-12-01"' .
                ',"is_recurring":true,"notification_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9X' .
                'YG90R5D3E","reason_code_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f1a","set' .
                'tle_date":"2021-12-01","status_code":101,"transaction_batch_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","verbiage":"APPROVED","void_date":"2021-12-01","batch":"2","terms_a' .
                'gree":true,"response_message":null,"return_date":"2021-12-01","trx_source_id":8' .
                ',"routing_number":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"modified_user_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","is' .
                '_token":true,"installment_total":1,"installment_counter":1,"account_vault_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'account_vault":{"account_holder_name":"John Smith","account_vault_api_id":"acco' .
                'untvaultabcd","token_api_id":"tokenabcd","accountvault_c1":"accountvault custom' .
                ' 1","accountvault_c2":"accountvault custom 2","accountvault_c3":"accountvault c' .
                'ustom 3","token_c1":"token custom 1","token_c2":"token custom 2","token_c3":"to' .
                'ken custom 3","ach_sec_code":"WEB","billing_address":{"city":"Novi","state":"Mi' .
                'chigan","postal_code":"48375","phone":"3339998822","country":"USA"},"contact_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","identity_verification":{"d' .
                'l_state":"MI","dl_number":"1235567","ssn4":"8527","dob_year":"1980"},"location_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault_api_id":"previousaccount' .
                'vault123456","previous_token_api_id":"previousaccountvault123456","previous_acc' .
                'ount_vault_id":"11e95f8ec39de8fbdb0a4f1a","previous_token_id":"11e95f8ec39de8fb' .
                'db0a4f1a","previous_transaction_id":"11e95f8ec39de8fbdb0a4f1a","account_number"' .
                ':"545454545454545","terms_agree":true,"terms_agree_ip":"192.168.0.10","title":"' .
                'Test CC Account","token_import_id":"11e95f8ec39de8fbdb0a4f1a","secure_directory' .
                '_server_transaction_id":"d65e93c3-35ab-41ba-b307-767bfc19eae","secure_protocol_' .
                'version":2,"secure_auth_data":"vVwL7UNHCf8W8M2LAfvRChNHN7c%3D","secure_collecti' .
                'on_indicator":null,"three_ds_server_trans_id":"d65e93c3-35ab-41ba-b307-767bfc19' .
                'eae","acs_transaction_id":"13c701a3-5a88-4c45-89e9-ef65e50a8bf9","_joi":{},"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","account_type":"checking","active":true,"cau_summar' .
                'y_status_id":1,"created_ts":1422040992,"e_serial_number":"1234567890","e_track_' .
                'data":null,"e_format":null,"e_keyed_data":null,"expiring_in_months":null,"exp_d' .
                'ate":"0722","first_six":"700953","has_recurring":false,"last_four":"3657","modi' .
                'fied_ts":1422040992,"payment_method":"cc","ticket":null,"track_data":null,"crea' .
                'ted_user_id":"11e95f8ec39de8fbdb0a4f1a","cau_last_updated_ts":1422040992,"routi' .
                'ng_number":"051904524"},"quick_invoice":{"location_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","title":"My terminal","cc_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"ach_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","due_date":"2021-12-01' .
                '","item_list":[{"name":"Bread","amount":2015}],"allow_overpayment":true,"bank_f' .
                'unded_only_override":true,"email":"email@domain.com","contact_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","contact_api_id":"contact12345","quick_invoice_api_id":"quickinvo' .
                'ice12345","customer_id":"11e95f8ec39de8fbdb0a4f1a","expire_date":"2021-12-01","' .
                'allow_partial_pay":true,"attach_files_to_email":true,"send_email":true,"invoice' .
                '_number":"invoice12345","item_header":"Quick invoice header sample","item_foote' .
                'r":"Thank you","amount_due":245.36,"notification_email":"email@domain.com","sta' .
                'tus_id":1,"status_code":1,"note":"some note","notification_days_before_due_date' .
                '":3,"notification_days_after_due_date":7,"notification_on_due_date":true,"send_' .
                'text_to_pay":true,"files":[{}],"remaining_balance":245.36,"single_payment_min_a' .
                'mount":500,"single_payment_max_amount":500000,"cell_phone":"3339998822","tags":' .
                '["Walk-in Customer"],"quick_invoice_c1":"custom-data-1","quick_invoice_c2":"cus' .
                'tom-data-2","quick_invoice_c3":"custom-data-3","auto_reopen":true,"id":"11e95f8' .
                'ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"active":true,"payment_status_id":1,"is_active":true},"log_emails":[{"subject"' .
                ':"Payment Receipt - 12skiestech","body":"This email is being sent from a server' .
                '.","source_address":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return' .
                '_path":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"01000' .
                '17e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","reason_sent":"Contact Email","reason_model":"Transaction","re' .
                'ason_model_id":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@ze' .
                'amster.com>","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"is_void' .
                'able":true,"is_reversible":true,"is_refundable":true,"is_completable":true,"is_' .
                'settled":true,"created_user":{"account_number":"5454545454545454","branding_dom' .
                'ain_url":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fort' .
                'is Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth' .
                '":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com' .
                '","email_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last_' .
                'name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":"' .
                '5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":nul' .
                'l,"terms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_' .
                'page":"dashboard","page_size":2,"report_export_type":"csv","process_method":"vi' .
                'rtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{use' .
                'r_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_' .
                'code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","status_code":1,"api_only":false,"is_invitation":false,"address":{"city":"Nov' .
                'i","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0' .
                'a4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts"' .
                ':1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date' .
                '_time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_response_' .
                'body_ts":1422040992},"location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1' .
                '422040992,"modified_ts":1422040992,"account_number":"5454545454545454","address' .
                '":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_d' .
                'omain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"' .
                'default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda"' .
                ',"email_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"loca' .
                'tion-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custo' .
                'm 1","location_c2":"custom 2","location_c3":"custom data 3","name":"Sample Comp' .
                'any Headquarters","office_phone":"2481234567","office_ext_phone":"1021021209","' .
                'tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_not' .
                'es":true,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"location_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"conta' .
                'ct":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","c' .
                'ontact_api_id":"137","first_name":"John","last_name":"Smith","cell_phone":"3339' .
                '998822","balance":245.36,"address":{"city":"Novi","state":"Michigan","postal_co' .
                'de":"48375","country":"US"},"company_name":"Fortis Payment Systems, LLC","heade' .
                'r_message":"This is a sample message for you","date_of_birth":"2021-12-01","ema' .
                'il_trx_receipt":true,"home_phone":"3339998822","office_phone":"3339998822","off' .
                'ice_phone_ext":"5","header_message_type":0,"update_if_exists":1,"contact_c1":"a' .
                'ny","contact_c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142' .
                '2040992,"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"changelogs' .
                '":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","' .
                'model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","' .
                'changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"164' .
                '3616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com' .
                '","first_name":"Bob","last_name":"Fairview"}}],"product_transaction":{"processo' .
                'r_version":"1_0_0","title":"My terminal","payment_method":"cc","processor":"zga' .
                'te","mcc":"1111","tax_surcharge_config":2,"partner":"standalone","location_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{},"vt_clerk_number"' .
                ':true,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allow_debit":true,"ach_' .
                'allow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt_street":true,"vt_z' .
                'ip":true,"vt_order_num":true,"vt_enable":true,"receipt_show_contact_name":true,' .
                '"display_avs":true,"card_type_visa":true,"card_type_mc":true,"card_type_disc":t' .
                'rue,"card_type_amex":true,"card_type_diners":true,"card_type_jcb":true,"card_ty' .
                'pe_ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt_food_stamp":true,"invoice' .
                '_location":true,"allow_partial_authorization":true,"allow_recurring_partial_aut' .
                'horization":true,"auto_decline_cvv":true,"auto_decline_street":true,"auto_decli' .
                'ne_zip":true,"split_payments_allow":true,"vt_show_custom_fields":true,"receipt_' .
                'show_custom_fields":true,"vt_override_sales_tax_allowed":true,"vt_enable_sales_' .
                'tax":true,"vt_require_zip":true,"vt_require_street":true,"auto_decline_cavv":tr' .
                'ue,"current_batch":34,"dup_check_per_batch":null,"paylink_allow":false,"quick_i' .
                'nvoice_allow":false,"level3_allow":false,"payfac_enable":false,"enable_3ds":fal' .
                'se,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":fal' .
                'se,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_commerce":false,"level3' .
                '_default":{"destination_country_code":"840","duty_amount":0,"freight_amount":0,' .
                '"national_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ12345","shipto_zip_code' .
                '":"MI48335","tax_amount":0,"tax_exempt":"0","customer_vat_registration":"123456' .
                '78","merchant_vat_registration":"123456","order_date":"171006","summary_commodi' .
                'ty_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat1234","line_items":[{"' .
                'alternate_tax_id":"1234","debit_credit":"C","description":"cool drink","discoun' .
                't_amount":10,"discount_rate":11,"product_code":"coke12345678","quantity":5,"tax' .
                '_amount":3,"tax_rate":0,"tax_type_applied":"22","tax_type_id":"a1","unit_code":' .
                '"gll","unit_cost":10,"commodity_code":"cc123456","other_tax_amount":0}]},"cau_s' .
                'ubscribe_type_id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","p' .
                'roduct_billing_group_id":"nofees","account_number":"12345678","run_avs_on_accou' .
                'ntvault_create":false,"accountvault_expire_notification_email_enable":false,"de' .
                'bit_allow_void":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_' .
                'show_currency":true,"receipt_show_currency":false,"allow_blind_refund":false,"v' .
                't_show_company_name":false,"receipt_show_company_name":false,"bank_funded_only"' .
                ':false,"require_cvv_on_keyed_cnp":true,"require_cvv_on_tokenized_cnp":true,"sho' .
                'w_secondary_amount":false,"allow_secondary_amount":false,"show_google_pay":true' .
                ',"show_apple_pay":true,"batch_risk_config":{},"currency_code":840,"enable_ach_v' .
                'alidation":false,"enable_ach_retry":false,"id":"11e95f8ec39de8fbdb0a4f1a","acti' .
                've":true,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","product_' .
                'transaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary_amount_allowed":fa' .
                'lse,"fortis_id":"8149742","product_billing_group_code":"nofees","cau_subscribe_' .
                'type_code":0},"all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My' .
                ' terminal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts' .
                '":1422040992}],"tagTransactions":[{"id":"11e95f8ec39de8fbdb0a4f1a","tag_id":"Ta' .
                'g ID","transaction_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modi' .
                'fied_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user' .
                '_id":"11e95f8ec39de8fbdb0a4f1a"}],"declined_recurring_notification":{"id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","modified_ts":1422040992,"modified_user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a"},"payment_recurring_notification":{"id":"11e95f8ec39de8fbdb0a4f1a","created' .
                '_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_ts":1422' .
                '040992,"modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"developer_company":{"tit' .
                'le":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":14' .
                '22040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"terminal":{"location_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","default_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","terminal_application_id":"11e95f8ec39de8fbdb0a4f1a","terminal_cvm_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","terminal_manufacturer_code":"1","title":"My terminal","ma' .
                'c_address":"3D:F2:C9:A6:B3:4F","local_ip_address":"192.168.0.10","port":10009,"' .
                'serial_number":"1234567890","terminal_number":"973456789012367","terminal_timeo' .
                'uts":{"card_entry_timeout":47,"device_terms_prompt_timeout":30,"overall_timeout' .
                '":125,"pin_entry_timeout":40,"signature_input_timeout":35,"signature_submit_tim' .
                'eout":38,"status_display_time":12,"tip_cashback_timeout":25,"transaction_timeou' .
                't":17},"tip_percents":{"percent_1":0,"percent_2":2,"percent_3":99},"header_line' .
                '_1":"line 1 sample","header_line_2":"line 2 sample","header_line_3":"line 3 sam' .
                'ple","header_line_4":"line 4 sample","header_line_5":"line 5 sample","trailer_l' .
                'ine_1":"trailer 1 sample","trailer_line_2":"trailer 2 sample","trailer_line_3":' .
                '"trailer 3 sample","trailer_line_4":"trailer 4 sample","trailer_line_5":"traile' .
                'r 5 sample","default_checkin":"2021-12-01","default_checkout":"2021-12-01","def' .
                'ault_room_rate":56,"default_room_number":"303","debit":false,"emv":false,"cashb' .
                'ack_enable":false,"print_enable":false,"sig_capture_enable":false,"is_provision' .
                'ed":false,"tip_enable":false,"validated_decryption":false,"communication_type":' .
                '"http","active":true,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"m' .
                'odified_ts":1422040992,"last_registration_ts":1422040992,"created_user_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"hosted_p' .
                'ayment_page":{"user_id":"11e95f8ec39de8fbdb0a4f1a","location_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","location_api_id":null,"product_transaction_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","title":"Sample title","redirect_url_delay":15,"min_payment_amount":0,' .
                '"max_payment_amount":9999999999,"redirect_url_on_approve":null,"redirect_url_on' .
                '_decline":null,"field_configuration":{"css_mini":true,"stack":"vertical","heade' .
                'r":{"settings":{"enabled":true,"columns":1,"rows":1},"fields":[{"id":"transacti' .
                'on_amount","label":"Header","field_type":"heading","position":["1"],"required":' .
                'true,"readonly":true,"visible":true}]},"body":{"settings":{"enabled":true,"colu' .
                'mns":1,"rows":1},"fields":[{"id":"transaction_amount","label":"Header","field_t' .
                'ype":"heading","position":["1"],"required":true,"readonly":true,"visible":true}' .
                ']},"footer":{"settings":{"enabled":true,"columns":1,"rows":1},"fields":[{"id":"' .
                'transaction_amount","label":"Header","field_type":"heading","position":["1"],"r' .
                'equired":true,"readonly":true,"visible":true}]}},"encryption_key":null,"stylesh' .
                'eet_url":null,"parent_send_message":true,"hide_optional_fields":true,"id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created' .
                '_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a"},"transaction_level3":{"id":"11e95f8ec39de8fbdb0a4f1a","transaction_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","level3_data":{"destination_country_code":"840","duty_a' .
                'mount":0,"freight_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code' .
                '":"AZ1234","shipto_zip_code":"FL1234","tax_amount":10,"tax_exempt":"0","custome' .
                'r_vat_registration":"12345678","merchant_vat_registration":"123456","order_date' .
                '":"171006","summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number"' .
                ':"vat1234","line_items":[{"description":"cool drink","commodity_code":"cc123456' .
                '","discount_amount":0,"other_tax_amount":0,"product_code":"fanta123456","quanti' .
                'ty":12,"tax_amount":4,"tax_rate":0,"unit_code":"gll","unit_cost":3,"alternate_t' .
                'ax_id":"1234","debit_credit":"C","discount_rate":11,"tax_type_applied":"22","ta' .
                'x_type_id":"11"}]}},"developer_company_id":"Sample Developer Company ID","trans' .
                'action_histories":[{"transaction_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec' .
                '39de8fbdb0a4f1a","status_id":101,"event_date_ts":1422040992,"location_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}],"surch' .
                'arge_transaction":{"id":"11e95f8ec39de8fbdb0a4f1a","model_name":"Model Name","t' .
                'ransaction_id":"11e95f8ec39de8fbdb0a4f1a","surcharge_fee":0,"surcharge_rate":0,' .
                '"surcharge_amount":null,"surcharge_transaction_min":null,"surcharge_transaction' .
                '_max":null,"created":1422040992,"modified":1422040992,"created_user_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"surcharge":' .
                '{"surcharge_fee":10,"surcharge_rate":1,"product_transaction_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","apply_to_user_type_id":"11e95f8ec39de8fbdb0a4f1a","title":null,"su' .
                'rcharge_label":null,"surcharge_transaction_product_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","id":"11e95f8ec39de8fbdb0a4f1a","created_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"modified_user_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modifie' .
                'd_ts":1422040992},"signature":{"signature":"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAY' .
                'AAAAOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4' .
                'OIXtaXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYV' .
                'VW6WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FN' .
                'rCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnq' .
                'feQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b4NLU' .
                '3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6aSr1' .
                'UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYax7Em' .
                'SXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUS' .
                'Px+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk' .
                '7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+S' .
                'lRj9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDc' .
                'ERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGD' .
                'RX+EC0ah++pNrAAAAAElFTkSuQmCC","resource":"Transaction","resource_id":"11e95f8e' .
                'c39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modi' .
                'fied_ts":1422040992},"reason_code":{"id":50,"title":"Sample Title"},"type":{"id' .
                '":50,"title":"Sample Title"},"status":{"id":50,"title":"Sample Title"},"transac' .
                'tion_batch":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"product_t' .
                'ransaction_id":"11e95f8ec39de8fbdb0a4f1a","processing_status_id":2,"batch_num":' .
                '4,"is_open":0,"settlement_file_name":"settement_file.txt","batch_close_ts":1531' .
                '423693,"batch_close_detail":"BATCH_MISMATCH","total_sale_amount":2342,"total_sa' .
                'le_count":21,"total_refund_amount":2342,"total_refund_count":18,"total_void_amo' .
                'unt":2342,"total_void_count":17,"total_blind_refund_amount":2342,"total_blind_r' .
                'efund_count":16},"transaction_splits":[{"transaction_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","contact_id":"11e95f8ec39de8fbdb0a4f1a","amount":10,"id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}' .
                '],"postback_logs":[{"id":"11e95f8ec39de8fbdb0a4f1a","postback_config_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","next_run_ts":14' .
                '22040992,"created_ts":1422040992,"model_id":"11e95f8ec39de8fbdb0a4f1a"}],"curre' .
                'ncy_type":{"id":50,"title":"Sample Title"},"transaction_references":[{"id":"11e' .
                '95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de' .
                '8fbdb0a4f1a"}],"rejected_transaction_ach_retries":[{"rejected_transaction_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","retry_transaction_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","return_fee_transaction_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"re' .
                'turn_fee_transaction_ach_retry":{"rejected_transaction_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","retry_transaction_id":"11e95f8ec39de8fb' .
                'db0a4f1a","return_fee_transaction_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1' .
                '422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"retry_transaction_ach_' .
                'retry":{"rejected_transaction_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","retry_transaction_id":"11e95f8ec39de8fbdb0a4f1a","return_fee_tra' .
                'nsaction_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a"},"saved_account":{"account_holder_name":"John Smi' .
                'th","account_vault_api_id":"accountvaultabcd","token_api_id":"tokenabcd","accou' .
                'ntvault_c1":"accountvault custom 1","accountvault_c2":"accountvault custom 2","' .
                'accountvault_c3":"accountvault custom 3","token_c1":"token custom 1","token_c2"' .
                ':"token custom 2","token_c3":"token custom 3","ach_sec_code":"WEB","billing_add' .
                'ress":{"city":"Novi","state":"Michigan","postal_code":"48375","phone":"33399988' .
                '22","country":"USA"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123' .
                '456","identity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":"852' .
                '7","dob_year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_accoun' .
                't_vault_api_id":"previousaccountvault123456","previous_token_api_id":"previousa' .
                'ccountvault123456","previous_account_vault_id":"11e95f8ec39de8fbdb0a4f1a","prev' .
                'ious_token_id":"11e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","account_number":"545454545454545","terms_agree":true,"terms_ag' .
                'ree_ip":"192.168.0.10","title":"Test CC Account","token_import_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","secure_directory_server_transaction_id":"d65e93c3-35ab-41ba-b30' .
                '7-767bfc19eae","secure_protocol_version":2,"secure_auth_data":"vVwL7UNHCf8W8M2L' .
                'AfvRChNHN7c%3D","secure_collection_indicator":null,"three_ds_server_trans_id":"' .
                'd65e93c3-35ab-41ba-b307-767bfc19eae","acs_transaction_id":"13c701a3-5a88-4c45-8' .
                '9e9-ef65e50a8bf9","_joi":{},"id":"11e95f8ec39de8fbdb0a4f1a","account_type":"che' .
                'cking","active":true,"cau_summary_status_id":1,"created_ts":1422040992,"e_seria' .
                'l_number":"1234567890","e_track_data":null,"e_format":null,"e_keyed_data":null,' .
                '"expiring_in_months":null,"exp_date":"0722","first_six":"700953","has_recurring' .
                '":false,"last_four":"3657","modified_ts":1422040992,"payment_method":"cc","tick' .
                'et":null,"track_data":null,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","cau_la' .
                'st_updated_ts":1422040992,"routing_number":"051904524"},"balances":[{"amount":1' .
                '000}]}],"links":{"type":"Links","first":"/v1/endpoint?page[size]=10&page[number' .
                ']=1","previous":"/v1/endpoint?page[size]=10&page[number]=5","next":"/v1/endpoin' .
                't?page[size]=10&page[number]=7","last":"/v1/endpoint?page[size]=10&page[number]' .
                '=42"},"pagination":{"type":"Pagination","total_count":423,"page_count":42,"page' .
                '_number":6,"page_size":10},"sort":{"type":"Sorting","fields":[{"field":"last_na' .
                'me","order":"asc"}]}}'
            )))
            ->assert();
    }
}
