<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\UsersController;
use FortisAPILib\Exceptions;

class UsersControllerTest extends BaseTestController
{
    /**
     * @var UsersController UsersController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getUsersController();
    }

    public function testCreateANewAPIKey()
    {
        // Parameters for the API call
        $userId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createANewAPIKey($userId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(201)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(
                TestParam::object('{"type":"UserApiKey","data":{"user_api_key":"234bas8dfn8238f923w2"}}')
            ))
            ->assert();
    }

    public function testListAllUser()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllUser(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"UsersCollection","list":[{"account_number":"5454545454545454","brandi' .
                'ng_domain_url":"{branding_domain_url}","cell_phone":"3339998822","company_name"' .
                ':"Fortis Payment Systems, LLC","contact_id":"Sample contact ID","date_of_birth"' .
                ':"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com"' .
                ',"email_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last_n' .
                'ame":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":"5' .
                '","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null' .
                ',"terms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_p' .
                'age":"dashboard","page_size":2,"report_export_type":"csv","process_method":"vir' .
                'tual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user' .
                '_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_c' .
                'ode":100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"status_code":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi' .
                '","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":' .
                '1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_' .
                'time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_api_response_b' .
                'ody_ts":1422040992,"locations":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1' .
                '422040992,"modified_ts":1422040992,"account_number":"5454545454545454","address' .
                '":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_d' .
                'omain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"' .
                'default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda"' .
                ',"email_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"loca' .
                'tion-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custo' .
                'm 1","location_c2":"custom 2","location_c3":"custom data 3","name":"Sample Comp' .
                'any Headquarters","office_phone":"2481234567","office_ext_phone":"1021021209","' .
                'tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_not' .
                'es":true,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"location_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"}],"prim' .
                'ary_location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modifie' .
                'd_ts":1422040992,"account_number":"5454545454545454","address":{"city":"Novi","' .
                'state":"MI","postal_code":"48375","country":"US"},"branding_domain_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e6' .
                '08a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":' .
                '"email@domain.com","fax":"3339998822","location_api_id":"location-111111","loca' .
                'tion_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2"' .
                ':"custom 2","location_c3":"custom data 3","name":"Sample Company Headquarters",' .
                '"office_phone":"2481234567","office_ext_phone":"1021021209","tz":"America/New_Y' .
                'ork","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_con' .
                'tact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"' .
                'merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"received_emails":[{"sub' .
                'ject":"Payment Receipt - 12skiestech","body":"This email is being sent from a s' .
                'erver.","source_address":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","r' .
                'eturn_path":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"' .
                '0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","reason_sent":"Contact Email","reason_model":"Transaction' .
                '","reason_model_id":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma' .
                '.p@zeamster.com>","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"co' .
                'ntact":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332"' .
                ',"contact_api_id":"137","first_name":"John","last_name":"Smith","cell_phone":"3' .
                '339998822","balance":245.36,"address":{"city":"Novi","state":"Michigan","postal' .
                '_code":"48375","country":"US"},"company_name":"Fortis Payment Systems, LLC","he' .
                'ader_message":"This is a sample message for you","date_of_birth":"2021-12-01","' .
                'email_trx_receipt":true,"home_phone":"3339998822","office_phone":"3339998822","' .
                'office_phone_ext":"5","header_message_type":0,"update_if_exists":1,"contact_c1"' .
                ':"any","contact_c2":"anything","contact_c3":"something","parent_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","email":"email@domain.com","token_import_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":' .
                '1422040992,"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"isDelet' .
                'able":true,"active_notification_alerts":[{"location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","date_start":"2021-12-01 10:10:00","date_end":"2021-12-01 10:10:00","user_l' .
                'ocation":true,"user_contact":true,"include_children":true,"alert_type":1,"alert' .
                '_type_id":1,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_t' .
                's":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"' .
                '11e95f8ec39de8fbdb0a4f1a"}],"location_users":[{"location_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","user_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created' .
                '_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a"}],"auth_roles":[{"user_id":"11e95f8ec39de8fbdb0a4f1a","auth_role_code":110,' .
                '"code":83931,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"ch' .
                'angelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"C' .
                'REATE","model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0' .
                'a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_val' .
                'ue":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@do' .
                'main.com","first_name":"Bob","last_name":"Fairview"}}],"resources":{"title":"My' .
                ' terminal","priv":null,"resource_name":"v2.addons.iframe.get","id":5693,"last_u' .
                'sed_date":1422040992,"created_ts":1422040992,"modified_ts":1422040992},"domain"' .
                ':{"url":"fortispayrbyn9y.sandbox.zeamster.com","title":"Test Brand Domain Title' .
                ' 2","logo":"","support_email":"email@domain.com","allow_contact_signup":true,"a' .
                'llow_contact_registration":true,"allow_contact_login":true,"registration_fields' .
                '":["account_number"],"company_name":null,"nav_color":null,"button_primary_color' .
                '":null,"logo_background_color":null,"icon_background_color":null,"menu_text_bac' .
                'kground_color":null,"menu_text_color":null,"right_menu_background_color":null,"' .
                'right_menu_text_color":null,"button_primary_text_color":null,"nav_logo":null,"f' .
                'av_icon":null,"aes_key":null,"help_text":null,"email_reply_to":"email@domain.co' .
                'm","email":"email@domain.com","custom_javascript":null,"custom_theme":null,"cus' .
                'tom_css":null,"contact_user_default_entry_page":"dashboard","contact_user_defau' .
                'lt_auth_roles":[null],"custom_stylesheet_url":"https://127.0.0.1/receiver","id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992},"' .
                'created_user":{"account_number":"5454545454545454","branding_domain_url":"{bran' .
                'ding_domain_url}","cell_phone":"3339998822","company_name":"Fortis Payment Syst' .
                'ems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01",' .
                '"domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_re' .
                'ceipt":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith","' .
                'locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_loc' .
                'ation_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_condit' .
                'ion_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboar' .
                'd","page_size":2,"report_export_type":"csv","process_method":"virtual_terminal"' .
                ',"default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_' .
                'api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"pass' .
                'word":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_code"' .
                ':1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","state":"MI"' .
                ',"postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status"' .
                ':true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"mo' .
                'dified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accep' .
                'ted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03' .
                '-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_ts":142204' .
                '0992},"location_marketplaces":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","marke' .
                'tplace_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"user_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"cre' .
                'ated_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"email_blacklist":{"id":"11e95f8ec39' .
                'de8fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts":1422040992},"hel' .
                'ppage":{"user_type_code":100,"body":"Sample Body","title":"Sample Title","id":"' .
                '11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"cre' .
                'ated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a"}}],"links":{"type":"Links","first":"/v1/endpoint?page[size]=10&page[num' .
                'ber]=1","previous":"/v1/endpoint?page[size]=10&page[number]=5","next":"/v1/endp' .
                'oint?page[size]=10&page[number]=7","last":"/v1/endpoint?page[size]=10&page[numb' .
                'er]=42"},"pagination":{"type":"Pagination","total_count":423,"page_count":42,"p' .
                'age_number":6,"page_size":10},"sort":{"type":"Sorting","fields":[{"field":"last' .
                '_name","order":"asc"}]}}'
            )))
            ->assert();
    }

    public function testDeleteAUserRecord()
    {
        // Parameters for the API call
        $userId = '11e95f8ec39de8fbdb0a4f1a';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->deleteAUserRecord($userId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(204)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"User","data":{"account_number":"5454545454545454","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fortis Pay' .
                'ment Systems, LLC","contact_id":"Sample contact ID","date_of_birth":"2021-12-01' .
                '","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_' .
                'receipt":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith"' .
                ',"locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_l' .
                'ocation_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_cond' .
                'ition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashbo' .
                'ard","page_size":2,"report_export_type":"csv","process_method":"virtual_termina' .
                'l","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","use' .
                'r_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"pa' .
                'ssword":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_cod' .
                'e":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","state":"M' .
                'I","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","statu' .
                's":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"' .
                'modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_acc' .
                'epted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-' .
                '03-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_ts":1422' .
                '040992,"locations":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"m' .
                'odified_ts":1422040992,"account_number":"5454545454545454","address":{"city":"N' .
                'ovi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach"' .
                ':"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_repl' .
                'y_to":"email@domain.com","fax":"3339998822","location_api_id":"location-111111"' .
                ',"location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","locati' .
                'on_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Headquar' .
                'ters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"America' .
                '/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"sh' .
                'ow_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_t' .
                'ype":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"}],"primary_location' .
                '":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204' .
                '0992,"account_number":"5454545454545454","address":{"city":"Novi","state":"MI",' .
                '"postal_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e0' .
                '93242bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domai' .
                'n.com","fax":"3339998822","location_api_id":"location-111111","location_api_key' .
                '":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2",' .
                '"location_c3":"custom data 3","name":"Sample Company Headquarters","office_phon' .
                'e":"2481234567","office_ext_phone":"1021021209","tz":"America/New_York","parent' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":' .
                'true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","t' .
                'icket_hash_key":"A5F443CADF4AE34BBCAADF4"},"received_emails":[{"subject":"Payme' .
                'nt Receipt - 12skiestech","body":"This email is being sent from a server.","sou' .
                'rce_address":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":' .
                '"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bc' .
                'c530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fb' .
                'db0a4f1a","reason_sent":"Contact Email","reason_model":"Transaction","reason_mo' .
                'del_id":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.' .
                'com>","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"loc' .
                'ation_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_ap' .
                'i_id":"137","first_name":"John","last_name":"Smith","cell_phone":"3339998822","' .
                'balance":245.36,"address":{"city":"Novi","state":"Michigan","postal_code":"4837' .
                '5","country":"US"},"company_name":"Fortis Payment Systems, LLC","header_message' .
                '":"This is a sample message for you","date_of_birth":"2021-12-01","email_trx_re' .
                'ceipt":true,"home_phone":"3339998822","office_phone":"3339998822","office_phone' .
                '_ext":"5","header_message_type":0,"update_if_exists":1,"contact_c1":"any","cont' .
                'act_c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id' .
                '":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"' .
                'active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"isDeletable":true,"' .
                'active_notification_alerts":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","date_st' .
                'art":"2021-12-01 10:10:00","date_end":"2021-12-01 10:10:00","user_location":tru' .
                'e,"user_contact":true,"include_children":true,"alert_type":1,"alert_type_id":1,' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204099' .
                '2,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a"}],"location_users":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"auth_' .
                'roles":[{"user_id":"11e95f8ec39de8fbdb0a4f1a","auth_role_code":110,"code":83931' .
                ',"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"changelogs":[{' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","mode' .
                'l":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","chan' .
                'gelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616' .
                '000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","f' .
                'irst_name":"Bob","last_name":"Fairview"}}],"resources":{"title":"My terminal","' .
                'priv":null,"resource_name":"v2.addons.iframe.get","id":5693,"last_used_date":14' .
                '22040992,"created_ts":1422040992,"modified_ts":1422040992},"domain":{"url":"for' .
                'tispayrbyn9y.sandbox.zeamster.com","title":"Test Brand Domain Title 2","logo":"' .
                '","support_email":"email@domain.com","allow_contact_signup":true,"allow_contact' .
                '_registration":true,"allow_contact_login":true,"registration_fields":["account_' .
                'number"],"company_name":null,"nav_color":null,"button_primary_color":null,"logo' .
                '_background_color":null,"icon_background_color":null,"menu_text_background_colo' .
                'r":null,"menu_text_color":null,"right_menu_background_color":null,"right_menu_t' .
                'ext_color":null,"button_primary_text_color":null,"nav_logo":null,"fav_icon":nul' .
                'l,"aes_key":null,"help_text":null,"email_reply_to":"email@domain.com","email":"' .
                'email@domain.com","custom_javascript":null,"custom_theme":null,"custom_css":nul' .
                'l,"contact_user_default_entry_page":"dashboard","contact_user_default_auth_role' .
                's":[null],"custom_stylesheet_url":"https://127.0.0.1/receiver","id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992},"created_user' .
                '":{"account_number":"5454545454545454","branding_domain_url":"{branding_domain_' .
                'url}","cell_phone":"3339998822","company_name":"Fortis Payment Systems, LLC","c' .
                'ontact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,' .
                '"home_phone":"3339998822","first_name":"John","last_name":"Smith","locale":"en-' .
                'US","office_phone":"3339998822","office_ext_phone":"5","primary_location_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_condition_code":"2' .
                '0220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard","page_siz' .
                'e":2,"report_export_type":"csv","process_method":"virtual_terminal","default_te' .
                'rminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"23' .
                '4bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"password":null,"' .
                'zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only' .
                '":false,"is_invitation":false,"address":{"city":"Novi","state":"MI","postal_cod' .
                'e":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login' .
                '_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1' .
                '422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422' .
                '040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26' .
                '-0700","current_login":1422040992,"log_api_response_body_ts":1422040992},"locat' .
                'ion_marketplaces":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","marketplace_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"user_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a"}],"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1' .
                'a","isBlacklisted":true,"detail":true,"created_ts":1422040992},"helppage":{"use' .
                'r_type_code":100,"body":"Sample Body","title":"Sample Title","id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }

    public function testViewSingleUserRecord()
    {
        // Parameters for the API call
        $userId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleUserRecord($userId, $expand, $fields);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"User","data":{"account_number":"5454545454545454","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fortis Pay' .
                'ment Systems, LLC","contact_id":"Sample contact ID","date_of_birth":"2021-12-01' .
                '","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_' .
                'receipt":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith"' .
                ',"locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_l' .
                'ocation_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_cond' .
                'ition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashbo' .
                'ard","page_size":2,"report_export_type":"csv","process_method":"virtual_termina' .
                'l","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","use' .
                'r_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"pa' .
                'ssword":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_cod' .
                'e":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","state":"M' .
                'I","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","statu' .
                's":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"' .
                'modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_acc' .
                'epted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-' .
                '03-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_ts":1422' .
                '040992,"locations":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"m' .
                'odified_ts":1422040992,"account_number":"5454545454545454","address":{"city":"N' .
                'ovi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach"' .
                ':"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_repl' .
                'y_to":"email@domain.com","fax":"3339998822","location_api_id":"location-111111"' .
                ',"location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","locati' .
                'on_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Headquar' .
                'ters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"America' .
                '/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"sh' .
                'ow_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_t' .
                'ype":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"}],"primary_location' .
                '":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204' .
                '0992,"account_number":"5454545454545454","address":{"city":"Novi","state":"MI",' .
                '"postal_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e0' .
                '93242bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domai' .
                'n.com","fax":"3339998822","location_api_id":"location-111111","location_api_key' .
                '":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2",' .
                '"location_c3":"custom data 3","name":"Sample Company Headquarters","office_phon' .
                'e":"2481234567","office_ext_phone":"1021021209","tz":"America/New_York","parent' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":' .
                'true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","t' .
                'icket_hash_key":"A5F443CADF4AE34BBCAADF4"},"received_emails":[{"subject":"Payme' .
                'nt Receipt - 12skiestech","body":"This email is being sent from a server.","sou' .
                'rce_address":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":' .
                '"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bc' .
                'c530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fb' .
                'db0a4f1a","reason_sent":"Contact Email","reason_model":"Transaction","reason_mo' .
                'del_id":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.' .
                'com>","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"loc' .
                'ation_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_ap' .
                'i_id":"137","first_name":"John","last_name":"Smith","cell_phone":"3339998822","' .
                'balance":245.36,"address":{"city":"Novi","state":"Michigan","postal_code":"4837' .
                '5","country":"US"},"company_name":"Fortis Payment Systems, LLC","header_message' .
                '":"This is a sample message for you","date_of_birth":"2021-12-01","email_trx_re' .
                'ceipt":true,"home_phone":"3339998822","office_phone":"3339998822","office_phone' .
                '_ext":"5","header_message_type":0,"update_if_exists":1,"contact_c1":"any","cont' .
                'act_c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id' .
                '":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"' .
                'active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"isDeletable":true,"' .
                'active_notification_alerts":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","date_st' .
                'art":"2021-12-01 10:10:00","date_end":"2021-12-01 10:10:00","user_location":tru' .
                'e,"user_contact":true,"include_children":true,"alert_type":1,"alert_type_id":1,' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204099' .
                '2,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a"}],"location_users":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"auth_' .
                'roles":[{"user_id":"11e95f8ec39de8fbdb0a4f1a","auth_role_code":110,"code":83931' .
                ',"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"changelogs":[{' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","mode' .
                'l":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","chan' .
                'gelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616' .
                '000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","f' .
                'irst_name":"Bob","last_name":"Fairview"}}],"resources":{"title":"My terminal","' .
                'priv":null,"resource_name":"v2.addons.iframe.get","id":5693,"last_used_date":14' .
                '22040992,"created_ts":1422040992,"modified_ts":1422040992},"domain":{"url":"for' .
                'tispayrbyn9y.sandbox.zeamster.com","title":"Test Brand Domain Title 2","logo":"' .
                '","support_email":"email@domain.com","allow_contact_signup":true,"allow_contact' .
                '_registration":true,"allow_contact_login":true,"registration_fields":["account_' .
                'number"],"company_name":null,"nav_color":null,"button_primary_color":null,"logo' .
                '_background_color":null,"icon_background_color":null,"menu_text_background_colo' .
                'r":null,"menu_text_color":null,"right_menu_background_color":null,"right_menu_t' .
                'ext_color":null,"button_primary_text_color":null,"nav_logo":null,"fav_icon":nul' .
                'l,"aes_key":null,"help_text":null,"email_reply_to":"email@domain.com","email":"' .
                'email@domain.com","custom_javascript":null,"custom_theme":null,"custom_css":nul' .
                'l,"contact_user_default_entry_page":"dashboard","contact_user_default_auth_role' .
                's":[null],"custom_stylesheet_url":"https://127.0.0.1/receiver","id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992},"created_user' .
                '":{"account_number":"5454545454545454","branding_domain_url":"{branding_domain_' .
                'url}","cell_phone":"3339998822","company_name":"Fortis Payment Systems, LLC","c' .
                'ontact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,' .
                '"home_phone":"3339998822","first_name":"John","last_name":"Smith","locale":"en-' .
                'US","office_phone":"3339998822","office_ext_phone":"5","primary_location_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_condition_code":"2' .
                '0220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard","page_siz' .
                'e":2,"report_export_type":"csv","process_method":"virtual_terminal","default_te' .
                'rminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"23' .
                '4bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"password":null,"' .
                'zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only' .
                '":false,"is_invitation":false,"address":{"city":"Novi","state":"MI","postal_cod' .
                'e":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login' .
                '_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1' .
                '422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422' .
                '040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26' .
                '-0700","current_login":1422040992,"log_api_response_body_ts":1422040992},"locat' .
                'ion_marketplaces":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","marketplace_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"user_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a"}],"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1' .
                'a","isBlacklisted":true,"detail":true,"created_ts":1422040992},"helppage":{"use' .
                'r_type_code":100,"body":"Sample Body","title":"Sample Title","id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }

    public function testViewSelfRecord()
    {
        // Parameters for the API call
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSelfRecord($expand, $fields);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"User","data":{"account_number":"5454545454545454","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","company_name":"Fortis Pay' .
                'ment Systems, LLC","contact_id":"Sample contact ID","date_of_birth":"2021-12-01' .
                '","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_' .
                'receipt":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith"' .
                ',"locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_l' .
                'ocation_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_cond' .
                'ition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashbo' .
                'ard","page_size":2,"report_export_type":"csv","process_method":"virtual_termina' .
                'l","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","use' .
                'r_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"pa' .
                'ssword":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_cod' .
                'e":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","state":"M' .
                'I","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","statu' .
                's":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"' .
                'modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_acc' .
                'epted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-' .
                '03-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_ts":1422' .
                '040992,"locations":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"m' .
                'odified_ts":1422040992,"account_number":"5454545454545454","address":{"city":"N' .
                'ovi","state":"MI","postal_code":"48375","country":"US"},"branding_domain_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach"' .
                ':"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_repl' .
                'y_to":"email@domain.com","fax":"3339998822","location_api_id":"location-111111"' .
                ',"location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","locati' .
                'on_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Headquar' .
                'ters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"America' .
                '/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"sh' .
                'ow_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_t' .
                'ype":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"}],"primary_location' .
                '":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204' .
                '0992,"account_number":"5454545454545454","address":{"city":"Novi","state":"MI",' .
                '"postal_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e0' .
                '93242bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domai' .
                'n.com","fax":"3339998822","location_api_id":"location-111111","location_api_key' .
                '":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2",' .
                '"location_c3":"custom data 3","name":"Sample Company Headquarters","office_phon' .
                'e":"2481234567","office_ext_phone":"1021021209","tz":"America/New_York","parent' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":' .
                'true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","t' .
                'icket_hash_key":"A5F443CADF4AE34BBCAADF4"},"received_emails":[{"subject":"Payme' .
                'nt Receipt - 12skiestech","body":"This email is being sent from a server.","sou' .
                'rce_address":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":' .
                '"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bc' .
                'c530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fb' .
                'db0a4f1a","reason_sent":"Contact Email","reason_model":"Transaction","reason_mo' .
                'del_id":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.' .
                'com>","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"loc' .
                'ation_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_ap' .
                'i_id":"137","first_name":"John","last_name":"Smith","cell_phone":"3339998822","' .
                'balance":245.36,"address":{"city":"Novi","state":"Michigan","postal_code":"4837' .
                '5","country":"US"},"company_name":"Fortis Payment Systems, LLC","header_message' .
                '":"This is a sample message for you","date_of_birth":"2021-12-01","email_trx_re' .
                'ceipt":true,"home_phone":"3339998822","office_phone":"3339998822","office_phone' .
                '_ext":"5","header_message_type":0,"update_if_exists":1,"contact_c1":"any","cont' .
                'act_c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id' .
                '":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"' .
                'active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"isDeletable":true,"' .
                'active_notification_alerts":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","date_st' .
                'art":"2021-12-01 10:10:00","date_end":"2021-12-01 10:10:00","user_location":tru' .
                'e,"user_contact":true,"include_children":true,"alert_type":1,"alert_type_id":1,' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204099' .
                '2,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a"}],"location_users":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"auth_' .
                'roles":[{"user_id":"11e95f8ec39de8fbdb0a4f1a","auth_role_code":110,"code":83931' .
                ',"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"changelogs":[{' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","mode' .
                'l":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","chan' .
                'gelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616' .
                '000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","f' .
                'irst_name":"Bob","last_name":"Fairview"}}],"resources":{"title":"My terminal","' .
                'priv":null,"resource_name":"v2.addons.iframe.get","id":5693,"last_used_date":14' .
                '22040992,"created_ts":1422040992,"modified_ts":1422040992},"domain":{"url":"for' .
                'tispayrbyn9y.sandbox.zeamster.com","title":"Test Brand Domain Title 2","logo":"' .
                '","support_email":"email@domain.com","allow_contact_signup":true,"allow_contact' .
                '_registration":true,"allow_contact_login":true,"registration_fields":["account_' .
                'number"],"company_name":null,"nav_color":null,"button_primary_color":null,"logo' .
                '_background_color":null,"icon_background_color":null,"menu_text_background_colo' .
                'r":null,"menu_text_color":null,"right_menu_background_color":null,"right_menu_t' .
                'ext_color":null,"button_primary_text_color":null,"nav_logo":null,"fav_icon":nul' .
                'l,"aes_key":null,"help_text":null,"email_reply_to":"email@domain.com","email":"' .
                'email@domain.com","custom_javascript":null,"custom_theme":null,"custom_css":nul' .
                'l,"contact_user_default_entry_page":"dashboard","contact_user_default_auth_role' .
                's":[null],"custom_stylesheet_url":"https://127.0.0.1/receiver","id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992},"created_user' .
                '":{"account_number":"5454545454545454","branding_domain_url":"{branding_domain_' .
                'url}","cell_phone":"3339998822","company_name":"Fortis Payment Systems, LLC","c' .
                'ontact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,' .
                '"home_phone":"3339998822","first_name":"John","last_name":"Smith","locale":"en-' .
                'US","office_phone":"3339998822","office_ext_phone":"5","primary_location_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_condition_code":"2' .
                '0220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard","page_siz' .
                'e":2,"report_export_type":"csv","process_method":"virtual_terminal","default_te' .
                'rminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"23' .
                '4bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"password":null,"' .
                'zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only' .
                '":false,"is_invitation":false,"address":{"city":"Novi","state":"MI","postal_cod' .
                'e":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login' .
                '_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1' .
                '422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422' .
                '040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26' .
                '-0700","current_login":1422040992,"log_api_response_body_ts":1422040992},"locat' .
                'ion_marketplaces":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","marketplace_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"user_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a"}],"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1' .
                'a","isBlacklisted":true,"detail":true,"created_ts":1422040992},"helppage":{"use' .
                'r_type_code":100,"body":"Sample Body","title":"Sample Title","id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }

    public function testRemoveVerification()
    {
        // Parameters for the API call
        $userId = '';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->removeVerification($userId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(204)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"RemoveVerification","data":{"id":"11e95f8ec39de8fbdb0a4f1a","user_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","hash":"123456781234567812345678","created_ts":1422' .
                '040992}}'
            )))
            ->assert();
    }

    public function testSendVerification()
    {
        // Parameters for the API call
        $userId = '';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->sendVerification($userId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(201)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"SendVerification","data":{"id":"11e95f8ec39de8fbdb0a4f1a","user_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","hash":"123456781234567812345678","created_ts":142204' .
                '0992}}'
            )))
            ->assert();
    }
}
